apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-db-credentials

type: Opaque
data:
  username: c2ltcGxldmF0X3VzZXI=
  password: U2ltcGxlVmF0MTIz
  db-host: bXlzcWwtc2VydmVyLm15c3FsLXNlcnZlci1kZXY=

