apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-db-credentials

type: Opaque
data:
  username: c2ltcGxldmF0X2Rldl9kYl91c2Vy
  password: U2ltcGxlVmF0QDEyMw==
  db-host: bXlzcWwtc2VydmVyLm15c3FsLXNlcnZlci1kZXYuc3ZjLmNsdXN0ZXIubG9jYWw=

