
image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: ignore

tasks:
  - name: Restore Tailscale daemon
    command: |
      if [ -n "${TS_STATE_TAILSCALE_EXAMPLE}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TS_STATE_TAILSCALE_EXAMPLE}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled
  - name: Start application
    init: |
      eval $(gp env -e)
      npm install
    command: |
      REPO_NAME=simpleaccounts-backend
      API_IP=$(tailscale status | grep $REPO_NAME | cut -d " " -f 1)
      if [ "${API_IP}" ]; then
        echo "🐳 Connected to $REPO_NAME through Tailscale"
        SIMPLEVAT_HOST="http://$API_IP:5000/api" npm run start
      else
        echo "🐳 Failed to connect to $REPO_NAME. Make sure a $REPO_NAME workspace is active and logged into Tailscale."

        npm run start
      fi
    env:
      PORT: 3000
      NODE_ENV: development
  - name: Connect to Tailscale
    command: |
      if [ -n "${TS_STATE_TAILSCALE_EXAMPLE}" ]; then
        sudo -E tailscale up
      else
        sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)"
        # store the tailscale state into gitpod user
        gp env TS_STATE_TAILSCALE_EXAMPLE="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi
      exit
vscode:
  extensions:
    - ms-vscode.vscode-github-issue-notebooks
    - KnisterPeter.vscode-github
    - vscode.github-browser
    - codezombiech.gitignore

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    develop: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false