stages:          # List of stages for jobs, and their order of execution
  - npm-compile
  - npm-build
  - docker-build
  - dev-deploy
  - sit-approval
  - sit-deploy
  - prod-build
  - prod-deploy
variables: 
  IMAGE: datainn/simpleaccounts/simpleaccounts-frontend
  TAG: $VERSION_PREFIX.$CI_PIPELINE_ID

# Cache modules in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

npm-compile-job:       # This job runs in the build stage, which runs first.
  stage: npm-compile
  script:
    - CI="false"
    - echo "Compiling the code...!"
    - npm ci --cache .npm --prefer-offline
    # - npm ci --loglevel verbose
    - echo "Compile completed."
  allow_failure: false
  artifacts:
    paths:
      - "./node_modules"
    when: on_success
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - job_execution_timeout
  
npm-build-job:       # This job runs in the build stage, which runs first.
  stage: npm-build
  variables: 
    KUBERNETES_MEMORY_REQUEST: 2Gi
    KUBERNETES_HELPER_MEMORY_REQUEST: 2Gi
  dependencies:
    - "npm-compile-job"
  script:
    - CI="false"
    - echo "building the code...!"
    - npm run build
    - echo "build completed."
  allow_failure: false
  artifacts:
    paths:
      - "./build"
    when: on_success
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - job_execution_timeout

docker-build-job:   # This job runs in the test stage.
  stage: docker-build    # It only starts when the job in the build stage completes successfully.
  image: docker:20.10.16
  variables: 
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "Waiting for docker to initialise..."
    - i=0; while [ "$i" -lt 12 ]; do docker info && break; sleep 5; i=$(( i + 1 )) ; done
    - echo "Docker running"
    - echo "update version to $TAG"
  dependencies:
    - "npm-build-job"
  script:
    - echo "Docker build and push..."
    - docker build -t $REGISTRY_URL/$IMAGE:$TAG .
    - echo "$REGISTRY_PASS" | docker login $REGISTRY_URL --username $REGISTRY_USER --password-stdin
    - docker push $REGISTRY_URL/$IMAGE:$TAG
    - echo "Docker image pushed"
  rules:
    - if: $CI_PROJECT_NAMESPACE == 'datainn/simpleaccounts' && $CI_COMMIT_BRANCH == 'develop'
      when: on_success
    - when: never
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - job_execution_timeout

dev-deploy-job:      # This job runs in the deploy stage.
  stage: dev-deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application to following cluster..."
    - kubectl cluster-info --kubeconfig="$KUBECONFIG_DEV"
    - echo "Test deployment scripts..."
    - helm upgrade --install --values ./simpleaccounts-frontend/values.yaml --set simpleVatFrontendRelease=$TAG,image.repository.frontend.tag=$TAG,image.repository.frontend.imageName=$REGISTRY_URL/$IMAGE,maindomain=dev.app.simpleaccounts.io,simpleVatHost=https://dev-api.app.simpleaccounts.io,fullnameOverride=dev-frontend,serviceAccount.name=dev-deploy-robot-frontend,ingress.hosts[0].host=dev.app.simpleaccounts.io,ingress.hosts[0].paths[0]=/*,clusterIssuer=app-simpleaccounts-io-letsencrypt-prod,'ingress.annotations.cert-manager\.io/clusterissuer'=app-simpleaccounts-io-letsencrypt-prod,ingress.tls[0].secretName=dev-app-simpleaccounts-io-tls,ingress.tls[0].hosts[0]=dev-api.app.simpleaccounts.io,ingress.tls[0].hosts[1]=dev.app.simpleaccounts.io --wait --dry-run --debug --namespace dev --create-namespace dev-frontend ./simpleaccounts-frontend --kubeconfig="$KUBECONFIG_DEV"
    - echo "Deployment started scripts..."
    - helm upgrade --install --values ./simpleaccounts-frontend/values.yaml --set simpleVatFrontendRelease=$TAG,image.repository.frontend.tag=$TAG,image.repository.frontend.imageName=$REGISTRY_URL/$IMAGE,maindomain=dev.app.simpleaccounts.io,simpleVatHost=https://dev-api.app.simpleaccounts.io,fullnameOverride=dev-frontend,serviceAccount.name=dev-deploy-robot-frontend,ingress.hosts[0].host=dev.app.simpleaccounts.io,ingress.hosts[0].paths[0]=/*,clusterIssuer=app-simpleaccounts-io-letsencrypt-prod,'ingress.annotations.cert-manager\.io/clusterissuer'=app-simpleaccounts-io-letsencrypt-prod,ingress.tls[0].secretName=dev-app-simpleaccounts-io-tls,ingress.tls[0].hosts[0]=dev-api.app.simpleaccounts.io,ingress.tls[0].hosts[1]=dev.app.simpleaccounts.io --wait --namespace dev --create-namespace dev-frontend ./simpleaccounts-frontend --kubeconfig="$KUBECONFIG_DEV"
    - echo "Application successfully deployed."
  resource_group: dev
  environment:
    name: Development
    url: https://dev.app.simpleaccounts.io
    action: start
  allow_failure: false
  rules:
    - if: $CI_PROJECT_NAMESPACE == 'datainn/simpleaccounts' && $CI_COMMIT_BRANCH == 'develop'
      when: on_success
    - when: never
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - job_execution_timeout

approve-sit-deployment:
  stage: sit-approval
  script:
    - echo "Approve SIT Deployment"
  resource_group: test
  allow_failure: false
  rules:
    - if: $CI_PROJECT_NAMESPACE == 'datainn/simpleaccounts' && $CI_COMMIT_BRANCH == 'develop'
      when: manual
    - when: never
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - job_execution_timeout

sit1-deploy-job:      # This job runs in the deploy stage.
  stage: sit-deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application to following cluster..."
    - kubectl cluster-info --kubeconfig="$KUBECONFIG_DEV"
    - echo "Test deployment scripts..."
    - helm upgrade --install --values ./simpleaccounts-frontend/values.yaml --set simpleVatFrontendRelease=$TAG,image.repository.frontend.tag=$TAG,image.repository.frontend.imageName=$REGISTRY_URL/$IMAGE,maindomain=sit1.app.simpleaccounts.io,simpleVatHost=https://sit1-api.app.simpleaccounts.io,fullnameOverride=sit1-frontend,serviceAccount.name=sit1-deploy-robot-frontend,ingress.hosts[0].host=sit1.app.simpleaccounts.io,ingress.hosts[0].paths[0]=/*,clusterIssuer=app-simpleaccounts-io-letsencrypt-prod,'ingress.annotations.cert-manager\.io/clusterissuer'=app-simpleaccounts-io-letsencrypt-prod,ingress.tls[0].secretName=sit1-app-simpleaccounts-io-tls,ingress.tls[0].hosts[0]=sit1-api.app.simpleaccounts.io,ingress.tls[0].hosts[1]=sit1.app.simpleaccounts.io --wait --dry-run --debug --namespace sit1 --create-namespace sit1-frontend ./simpleaccounts-frontend --kubeconfig="$KUBECONFIG_DEV"
    - echo "Deployment started scripts..."
    - helm upgrade --install --values ./simpleaccounts-frontend/values.yaml --set simpleVatFrontendRelease=$TAG,image.repository.frontend.tag=$TAG,image.repository.frontend.imageName=$REGISTRY_URL/$IMAGE,maindomain=sit1.app.simpleaccounts.io,simpleVatHost=https://sit1-api.app.simpleaccounts.io,fullnameOverride=sit1-frontend,serviceAccount.name=sit1-deploy-robot-frontend,ingress.hosts[0].host=sit1.app.simpleaccounts.io,ingress.hosts[0].paths[0]=/*,clusterIssuer=app-simpleaccounts-io-letsencrypt-prod,'ingress.annotations.cert-manager\.io/clusterissuer'=app-simpleaccounts-io-letsencrypt-prod,ingress.tls[0].secretName=sit1-app-simpleaccounts-io-tls,ingress.tls[0].hosts[0]=sit1-api.app.simpleaccounts.io,ingress.tls[0].hosts[1]=sit1.app.simpleaccounts.io --wait --namespace sit1 --create-namespace sit1-frontend ./simpleaccounts-frontend --kubeconfig="$KUBECONFIG_DEV"
    - echo "Application successfully deployed."
  resource_group: SIT1
  environment:
    name: SIT1
    url: https://sit1.app.simpleaccounts.io
    action: start
  allow_failure: false
  rules:
    - if: $CI_PROJECT_NAMESPACE == 'datainn/simpleaccounts' && $CI_COMMIT_BRANCH == 'develop'
      when: on_success
    - when: never
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - job_execution_timeout

sit2-deploy-job:      # This job runs in the deploy stage.
  stage: sit-deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application to following cluster..."
    - kubectl cluster-info --kubeconfig="$KUBECONFIG_DEV"
    - echo "Test deployment scripts..."
    - helm upgrade --install --values ./simpleaccounts-frontend/values.yaml --set simpleVatFrontendRelease=$TAG,image.repository.frontend.tag=$TAG,image.repository.frontend.imageName=$REGISTRY_URL/$IMAGE,maindomain=sit2.app.simpleaccounts.io,simpleVatHost=https://sit2-api.app.simpleaccounts.io,fullnameOverride=sit2-frontend,serviceAccount.name=sit2-deploy-robot-frontend,ingress.hosts[0].host=sit2.app.simpleaccounts.io,ingress.hosts[0].paths[0]=/*,clusterIssuer=app-simpleaccounts-io-letsencrypt-prod,'ingress.annotations.cert-manager\.io/clusterissuer'=app-simpleaccounts-io-letsencrypt-prod,ingress.tls[0].secretName=sit2-app-simpleaccounts-io-tls,ingress.tls[0].hosts[0]=sit2-api.app.simpleaccounts.io,ingress.tls[0].hosts[1]=sit2.app.simpleaccounts.io --wait --dry-run --debug --namespace sit2 --create-namespace sit2-frontend ./simpleaccounts-frontend --kubeconfig="$KUBECONFIG_DEV"
    - echo "Deployment started scripts..."
    - helm upgrade --install --values ./simpleaccounts-frontend/values.yaml --set simpleVatFrontendRelease=$TAG,image.repository.frontend.tag=$TAG,image.repository.frontend.imageName=$REGISTRY_URL/$IMAGE,maindomain=sit2.app.simpleaccounts.io,simpleVatHost=https://sit2-api.app.simpleaccounts.io,fullnameOverride=sit2-frontend,serviceAccount.name=sit2-deploy-robot-frontend,ingress.hosts[0].host=sit2.app.simpleaccounts.io,ingress.hosts[0].paths[0]=/*,clusterIssuer=app-simpleaccounts-io-letsencrypt-prod,'ingress.annotations.cert-manager\.io/clusterissuer'=app-simpleaccounts-io-letsencrypt-prod,ingress.tls[0].secretName=sit2-app-simpleaccounts-io-tls,ingress.tls[0].hosts[0]=sit2-api.app.simpleaccounts.io,ingress.tls[0].hosts[1]=sit2.app.simpleaccounts.io --wait --namespace sit2 --create-namespace sit2-frontend ./simpleaccounts-frontend --kubeconfig="$KUBECONFIG_DEV"
    - echo "Application successfully deployed."
  resource_group: SIT2
  environment:
    name: SIT2
    url: https://sit2.app.simpleaccounts.io
    action: start
  allow_failure: false
  rules:
    - if: $CI_PROJECT_NAMESPACE == 'datainn/simpleaccounts' && $CI_COMMIT_BRANCH == 'develop'
      when: on_success
    - when: never
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - job_execution_timeout

sit-reports-deploy-job:      # This job runs in the deploy stage.
  stage: sit-deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application to following cluster..."
    - kubectl cluster-info --kubeconfig="$KUBECONFIG_DEV"
    - echo "Test deployment scripts..."
    - helm upgrade --install --values ./simpleaccounts-frontend/values.yaml --set simpleVatFrontendRelease=$TAG,image.repository.frontend.tag=$TAG,image.repository.frontend.imageName=$REGISTRY_URL/$IMAGE,maindomain=sit-reports.app.simpleaccounts.io,simpleVatHost=https://sit-reports-api.app.simpleaccounts.io,fullnameOverride=sit-reports-frontend,serviceAccount.name=sit-reports-deploy-robot-frontend,ingress.hosts[0].host=sit-reports.app.simpleaccounts.io,ingress.hosts[0].paths[0]=/*,clusterIssuer=app-simpleaccounts-io-letsencrypt-prod,'ingress.annotations.cert-manager\.io/clusterissuer'=app-simpleaccounts-io-letsencrypt-prod,ingress.tls[0].secretName=sit-reports-app-simpleaccounts-io-tls,ingress.tls[0].hosts[0]=sit-reports-api.app.simpleaccounts.io,ingress.tls[0].hosts[1]=sit-reports.app.simpleaccounts.io --wait --dry-run --debug --namespace sit-reports --create-namespace sit-reports-frontend ./simpleaccounts-frontend --kubeconfig="$KUBECONFIG_DEV"
    - echo "Deployment started scripts..."
    - helm upgrade --install --values ./simpleaccounts-frontend/values.yaml --set simpleVatFrontendRelease=$TAG,image.repository.frontend.tag=$TAG,image.repository.frontend.imageName=$REGISTRY_URL/$IMAGE,maindomain=sit-reports.app.simpleaccounts.io,simpleVatHost=https://sit-reports-api.app.simpleaccounts.io,fullnameOverride=sit-reports-frontend,serviceAccount.name=sit-reports-deploy-robot-frontend,ingress.hosts[0].host=sit-reports.app.simpleaccounts.io,ingress.hosts[0].paths[0]=/*,clusterIssuer=app-simpleaccounts-io-letsencrypt-prod,'ingress.annotations.cert-manager\.io/clusterissuer'=app-simpleaccounts-io-letsencrypt-prod,ingress.tls[0].secretName=sit-reports-app-simpleaccounts-io-tls,ingress.tls[0].hosts[0]=sit-reports-api.app.simpleaccounts.io,ingress.tls[0].hosts[1]=sit-reports.app.simpleaccounts.io --wait --namespace sit-reports --create-namespace sit-reports-frontend ./simpleaccounts-frontend --kubeconfig="$KUBECONFIG_DEV"
    - echo "Application successfully deployed."
  resource_group: SIT-Reports
  environment:
    name: SIT-Reports
    url: https://sit-reports.app.simpleaccounts.io
    action: start
  allow_failure: false
  rules:
    - if: $CI_PROJECT_NAMESPACE == 'datainn/simpleaccounts' && $CI_COMMIT_BRANCH == 'develop'
      when: on_success
    - when: never
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - job_execution_timeout

prod-build-job:   # This job runs in the test stage.
  stage: prod-build    # It only starts when the job in the build stage completes successfully.
  image: docker:20.10.16
  variables: 
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "Waiting for docker to initialise..."
    - i=0; while [ "$i" -lt 12 ]; do docker info && break; sleep 5; i=$(( i + 1 )) ; done
    - echo "Docker running"
    - echo "update version to $TAG"
    - NEXT_VERSION=$(($SA_VERSION+1))
    - apk add curl
    - curl --request PUT --header "PRIVATE-TOKEN:$GITLAB_API_TOKEN" "https://gitlab.datainn.io/api/v4/projects/5/variables/SA_VERSION" --form "value="$NEXT_VERSION
    - TAG=$PROD_VERSION_PREFIX.$SA_VERSION
  dependencies:
    - "npm-build-job"
  script:
    - echo "Docker build and push..."
    - docker build -t $REGISTRY_URL/$IMAGE:$TAG .
    - echo "$REGISTRY_PASS" | docker login $REGISTRY_URL --username $REGISTRY_USER --password-stdin
    - docker push $REGISTRY_URL/$IMAGE:$TAG
    - echo "Docker image pushed"
  after_script:
    - echo $TAG > ./tag.txt
    - echo $TAG
  allow_failure: false
  artifacts:
    paths:
      - "./tag.txt"
    when: on_success
  rules:
    - if: $CI_PROJECT_NAMESPACE == 'datainn/simpleaccounts' && $CI_COMMIT_BRANCH == 'master'
      when: on_success
    - when: never
  resource_group: prod
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - job_execution_timeout

prod-deploy-job:      # This job runs in the deploy stage.
  stage: prod-deploy  # It only runs when *both* jobs in the test stage complete successfully.
  before_script:
    - TAG=$(< ./tag.txt)
    - echo $TAG
  dependencies:
    - "prod-build-job"
  script:
    - echo "Deploying application to following cluster..."
    - kubectl cluster-info
    - echo "Test deployment scripts..."
    # - helm upgrade --install --values ./simpleaccounts-frontend/values.yaml --set simpleVatFrontendRelease=$TAG,image.repository.frontend.tag=$TAG,image.repository.frontend.imageName=$REGISTRY_URL/$IMAGE,maindomain=sit-reports.app.simpleaccounts.io,simpleVatHost=https://sit-reports-api.app.simpleaccounts.io,fullnameOverride=sit-reports-frontend,serviceAccount.name=sit-reports-deploy-robot-frontend,ingress.hosts[0].host=sit-reports.app.simpleaccounts.io,ingress.hosts[0].paths[0]=/*,clusterIssuer=app-simpleaccounts-io-letsencrypt-prod,'ingress.annotations.cert-manager\.io/clusterissuer'=app-simpleaccounts-io-letsencrypt-prod,ingress.tls[0].secretName=sit-reports-app-simpleaccounts-io-tls,ingress.tls[0].hosts[0]=sit-reports-api.app.simpleaccounts.io,ingress.tls[0].hosts[1]=sit-reports.app.simpleaccounts.io --wait --dry-run --debug --namespace sit-reports --create-namespace sit-reports-frontend ./simpleaccounts-frontend --kubeconfig="$KUBECONFIG_DEV"
    - echo "Deployment started scripts..."
    # - helm upgrade --install --values ./simpleaccounts-frontend/values.yaml --set simpleVatFrontendRelease=$TAG,image.repository.frontend.tag=$TAG,image.repository.frontend.imageName=$REGISTRY_URL/$IMAGE,maindomain=sit-reports.app.simpleaccounts.io,simpleVatHost=https://sit-reports-api.app.simpleaccounts.io,fullnameOverride=sit-reports-frontend,serviceAccount.name=sit-reports-deploy-robot-frontend,ingress.hosts[0].host=sit-reports.app.simpleaccounts.io,ingress.hosts[0].paths[0]=/*,clusterIssuer=app-simpleaccounts-io-letsencrypt-prod,'ingress.annotations.cert-manager\.io/clusterissuer'=app-simpleaccounts-io-letsencrypt-prod,ingress.tls[0].secretName=sit-reports-app-simpleaccounts-io-tls,ingress.tls[0].hosts[0]=sit-reports-api.app.simpleaccounts.io,ingress.tls[0].hosts[1]=sit-reports.app.simpleaccounts.io --wait --namespace sit-reports --create-namespace sit-reports-frontend ./simpleaccounts-frontend --kubeconfig="$KUBECONFIG_DEV"
    - echo "Application successfully deployed."
  resource_group: prod
  environment:
    name: prod
    url: https://sandbox.ae.simpleaccounts.io
    action: start
  allow_failure: false
  rules:
    - if: $CI_PROJECT_NAMESPACE == 'datainn/simpleaccounts' && $CI_COMMIT_BRANCH == 'master'
      when: on_success
    - when: never
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - job_execution_timeout