
image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: ignore

tasks:
  - name: Restore Tailscale daemon
    command: |
      if [ -n "${TS_STATE_TAILSCALE_EXAMPLE}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TS_STATE_TAILSCALE_EXAMPLE}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled
  - name: Start application
    init: |
      eval $(gp env -e)
      npm install
    command: |
      REPO_NAME=backend-service
      API_IP=$(tailscale status | grep $REPO_NAME | cut -d " " -f 1)
      if [ "${API_IP}" ]; then
        echo "🐳 Connected to $REPO_NAME through Tailscale"
        SIMPLEVAT_HOST="http://$API_IP:5000/api" npm run dev
      else
        echo "🐳 Failed to connect to $REPO_NAME. Make sure a $REPO_NAME workspace is active and logged into Tailscale."

        npm run dev
      fi
    env:
      PORT: 3000
      NODE_ENV: development
  - name: Connect to Tailscale
    command: |
      if [ -n "${TS_STATE_TAILSCALE_EXAMPLE}" ]; then
        sudo -E tailscale up
      else
        sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)"
        # store the tailscale state into gitpod user
        gp env TS_STATE_TAILSCALE_EXAMPLE="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi
      exit
vscode:
  extensions:
    - CodeStream.codestream
    - ms-vscode.vscode-github-issue-notebooks
    - GitHub.vscode-pull-request-github
    - KnisterPeter.vscode-github
    - vscode.github-browser
    - codezombiech.gitignore
