env: flex
runtime: custom

resources:
  cpu: 1
  memory_gb: 3.75
  
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
env_variables:
  SIMPLEVAT_DB_HOST: "simplevat-dev:us-central1:simplevat-dev-db"
  SIMPLEVAT_DB: "simplevat_db"
  SIMPLEVAT_DB_USER: "simplevat_user"
  SIMPLEVAT_DB_PASSWORD: "SimpleVat123$$"
  
