env: flex
runtime: custom

resources:
  cpu: 1
  memory_gb: 3.75

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
env_variables:
  SIMPLEVAT_DB_HOST: "34.68.185.169"
  SIMPLEVAT_DB: "simplevat_dev_db"
  SIMPLEVAT_DB_USER: "simplevat_user"
  SIMPLEVAT_DB_PASSWORD: "SimpleVat123$$"

