env: flex
runtime: custom

resources:
  cpu: 2
  disk_size_gb: 10.0
  memory_gb: 8

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 2000

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8

env_variables:
  SIMPLEVAT_DB_HOST: "34.68.185.169"
  SIMPLEVAT_DB: "simplevat_db"
  SIMPLEVAT_DB_USER: "proxyuser"
  SIMPLEVAT_DB_PASSWORD: "SimpleVat123$"
  SIMPLEVAT_TOKEN: "XXX"
