env: flex
service: simplevat-dev
runtime: custom

resources:
  cpu: 2
  disk_size_gb: 10.0
  memory_gb: 8
  
liveness_check:
  path: "/healthz"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  
readiness_check:
  path: "/healthz"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
servingStatus: SERVING
threadsafe: true
versionUrl: https://simplevat-dev.appspot.com

env_variables:
  SIMPLEVAT_DB_HOST: "34.68.185.169"
  SIMPLEVAT_DB: "simplevat_dev_db"
  SIMPLEVAT_DB_USER: "simplevat_user"
  SIMPLEVAT_DB_PASSWORD: "SimpleVat123$$"
  SIMPLEVAT_TOKEN: "XXX"
  
createTime: '2019-09-12T17:21:16Z'
createdBy: mohsin@simplevat.com
