name: SimpleVAT-Build
trigger:
- develop
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: ci_build_simplevat
    displayName: CI Build for SimpleVAT

    jobs:
    - job: build
      displayName: Build SimpleVAT Application
      timeoutInMinutes: 30

      steps:
      - task: Maven@3
        displayName: Maven Build
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'

  - stage: ci_push_simplevat
    displayName: CI Build for SimpleVAT
    dependsOn: ci_build_simplevat
    jobs:
    - job: Push
      displayName: Push SimpleVAT Application
      timeoutInMinutes: 30
      steps:
      - task: Docker@2
        displayName: Docker Build & Push
        inputs:
          containerRegistry: 'DataInnAzureContainerRegistryConnection'
          repository: 'simpleva'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest




