steps:
- name: maven:3.6.1-jdk-8-slim
  entrypoint: 'mvn'
  args: ['clean','install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/simplevat-dev/simplevat:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/simplevat-dev/simplevat:$TAG_NAME']    
images: ['gcr.io/simplevat-dev/simplevat:$TAG_NAME']
timeout: 2400s
options:
  machineType: 'N1_HIGHCPU_32'  
