steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean','install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/simplevat-cluster/simplevat', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/simplevat-cluster/simplevat']  
- name: 'gcr.io/simplevat-cluster/simplevat-bash-kube'
  args:
  - 'ls'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=simplevat-prod-cluster'   
images: ['gcr.io/simplevat-cluster/simplevat']
