steps:
- name: 'gcr.io/gtt-project-prod/simplevat-maven-builder'
  entrypoint: 'mvn'
  args: ['clean', 'package']
  id: mvn-build
- name: 'gcr.io/gtt-project-prod/simplevat-maven-builder'
  entrypoint: 'mvn'
  args: ['verify', 'sonar:sonar']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/gtt-project-prod/simplevat:$TAG_NAME', '.']
  id: docker-build
  waitFor:
  - mvn-build
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gtt-project-prod/simplevat:$TAG_NAME']
  id: docker-push
  waitFor:
  - docker-build
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'rolling-update'
    - 'simplevat-dev-rep'
    - '--image=gcr.io/gtt-project-prod/simplevat:$TAG_NAME'
    - '--namespace=simplevat-dev'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s-prod'
  waitFor:
  - docker-push
images: ['gcr.io/gtt-project-prod/simplevat:$TAG_NAME']
timeout: 2400s
options:
  machineType: 'N1_HIGHCPU_32'
