steps:
# Copy Maven dependencies to volume mavenrepo
- name: gcr.io/cloud-builders/gsutil
  volumes:
    - name: 'mavenrepo'
      path: '/root/.m2'
  args: ['cp', '-r', 'gs://com-simplevat-mavenrepo', '/root/.m2']
  id: copy-mvn-repo
- name: 'maven:3.6.3-jdk-8-slim'
  volumes:
    - name: 'mavenrepo'
      path: '/root/.m2'
  entrypoint: 'mvn'
  args: ['verify', 'sonar:sonar','clean', 'package']
  id: mvn-build
  waitFor:
  - copy-mvn-repo
# Preserve the Maven dependencies into the bucket
- name: gcr.io/cloud-builders/gsutil
  volumes:
    - name: 'mavenrepo'
      path: '/root/.m2'
  args: ['cp', '-r', '/root/.m2', 'gs://com-simplevat-mavenrepo']
  waitFor:
    - mvn-build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/gtt-project-prod/simplevat:$TAG_NAME', '.']
  id: docker-build
  waitFor:
  - mvn-build
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gtt-project-prod/simplevat:$TAG_NAME']
  id: docker-push
  waitFor:
  - docker-build
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'rolling-update'
    - 'simplevat-dev-rep'
    - '--image=gcr.io/gtt-project-prod/simplevat:$TAG_NAME'
    - '--namespace=simplevat-dev'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s-prod'
  waitFor:
  - docker-push
images: ['gcr.io/gtt-project-prod/simplevat:$TAG_NAME']
timeout: 2400s
