steps:
- name: 'gcr.io/gtt-k8s/simplevat-maven-builder'
  entrypoint: 'mvn'
  args: ['verify', 'sonar:sonar','clean','package']
  id: mvn-build
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:debug-edge'
  args:
    - --destination=gcr.io/gtt-k8s/simplevat:$TAG_NAME
    - --cache=true
  id: docker-build-push
  waitFor:
  - mvn-build
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'rolling-update'
    - 'simplevat-dev-rep'
    - '--image=gcr.io/gtt-k8s/simplevat:$TAG_NAME'
    - '--namespace=simplevat-dev'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: image-update-dev
  waitFor:
  - docker-build-push
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'patch'
    - 'ReplicationController'
    - 'simplevat-dev-rep'
    - '--type=''json'''
    - '-p=''[{"op": "replace", "path": "/spec/template/spec/containers/0/env/9/value", "value":"$TAG_NAME"}]'''
    - '--namespace=simplevat-dev'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: release-update-dev
  waitFor:
    - image-update-dev
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'scale'
    - '--replicas=0'
    - 'rc'
    - 'simplevat-dev-rep'
    - '--namespace=simplevat-dev'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: scale-down-dev
  waitFor:
    - release-update-dev
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'scale'
    - '--replicas=3'
    - 'rc'
    - 'simplevat-dev-rep'
    - '--namespace=simplevat-dev'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: scale-up-dev
  waitFor:
    - scale-down-dev
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'rolling-update'
    - 'simplevat-test-rep'
    - '--image=gcr.io/gtt-k8s/simplevat:$TAG_NAME'
    - '--namespace=simplevat-test'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: image-update-test
  waitFor:
    - docker-build-push
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'patch'
    - 'ReplicationController'
    - 'simplevat-test-rep'
    - '--type=''json'''
    - '-p=''[{"op": "replace", "path": "/spec/template/spec/containers/0/env/9/value", "value":"$TAG_NAME"}]'''
    - '--namespace=simplevat-test'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: release-update-test
  waitFor:
    - image-update-test
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'scale'
    - '--replicas=0'
    - 'rc'
    - 'simplevat-test-rep'
    - '--namespace=simplevat-test'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: scale-down-test
  waitFor:
    - release-update-test
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'scale'
    - '--replicas=3'
    - 'rc'
    - 'simplevat-test-rep'
    - '--namespace=simplevat-test'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: scale-up-test
  waitFor:
    - scale-down-test
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'rolling-update'
    - 'simplevat-waqas-rep'
    - '--image=gcr.io/gtt-k8s/simplevat:$TAG_NAME'
    - '--namespace=simplevat-test'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: image-update-test-waqas
  waitFor:
    - docker-build-push
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'patch'
    - 'ReplicationController'
    - 'simplevat-waqas-rep'
    - '--type=''json'''
    - '-p=''[{"op": "replace", "path": "/spec/template/spec/containers/0/env/9/value", "value":"$TAG_NAME"}]'''
    - '--namespace=simplevat-test'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: release-update-test-waqas
  waitFor:
    - image-update-test-waqas
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'scale'
    - '--replicas=0'
    - 'rc'
    - 'simplevat-waqas-rep'
    - '--namespace=simplevat-test'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: scale-down-test-waqas
  waitFor:
    - release-update-test-waqas
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'scale'
    - '--replicas=3'
    - 'rc'
    - 'simplevat-waqas-rep'
    - '--namespace=simplevat-test'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s'
  id: scale-up-test-waqas
  waitFor:
    - scale-down-test-waqas
options:
  machineType: 'N1_HIGHCPU_8'
timeout: 2400s
