steps:
- name: maven:3.6.1-jdk-8-slim
  entrypoint: 'mvn'
  args: ['install']
  id: mvn-build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/simplevat-dev/simplevat:$TAG_NAME', '.']
  id: docker-build
  waitFor:
  - mvn-build
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/simplevat-dev/simplevat:$TAG_NAME']
  id: docker-push
  waitFor:
  - docker-build
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--image-url', 'gcr.io/simplevat-dev/simplevat:$TAG_NAME', '--project', 'simplevat-dev', '--version', '$TAG_NAME', '--promote','--stop-previous-version']
  id: gae-deploy
  waitFor:
  - docker-push
- name: 'gcr.io/simplevat-dev/simplevat-bash-kube'
  args:
  - 'bash'
  - './deploy/rolling-update-new-release.bash'
  - '$TAG_NAME'
  - 'dev'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=simplevat-dev'
  waitFor:
  - docker-push
images: ['gcr.io/simplevat-dev/simplevat:$TAG_NAME']
timeout: 2400s
options:
  machineType: 'N1_HIGHCPU_32'
