steps:
- name: 'gcr.io/gtt-project-prod/simplevat-maven-builder'
  entrypoint: 'mvn'
  args: ['package', '-X']
  id: mvn-build
  waitFor: ['-']
#- name: 'gcr.io/gtt-project-prod/simplevat-maven-builder'
#  entrypoint: 'mvn'
#  args: ['verify', 'sonar:sonar','-X']
#  id: mvn-verify-sonar
#  waitFor: ['-']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '--tag=gcr.io/gtt-project-prod/simplevat:$TAG_NAME', '.']
#  id: docker-build
#  waitFor:
#  - mvn-build
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/gtt-project-prod/simplevat:$TAG_NAME']
#  id: docker-push
#  waitFor:
#  - docker-build
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/gtt-project-prod/simplevat:$TAG_NAME
    - --cache=true
  id: docker-build-push
  waitFor:
  - mvn-build
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'rolling-update'
    - 'simplevat-dev-rep'
    - '--image=gcr.io/gtt-project-prod/simplevat:$TAG_NAME'
    - '--namespace=simplevat-dev'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gtt-k8s-prod'
  waitFor:
  - docker-build-push
timeout: 2400s
options:
  machineType: 'N1_HIGHCPU_8'
