apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ReplicationController","metadata":{"annotations":{},"labels":{"app":"simplevat"},"name":"simplevat-rc-dev","namespace":"simplevat-dev"},"spec":{"replicas":3,"selector":{"app":"simplevat"},"template":{"metadata":{"labels":{"app":"simplevat"}},"spec":{"containers":[{"env":[{"name":"SIMPLEVAT_SMTP_USER","value":"support@simplevat.com"},{"name":"SIMPLEVAT_SMTP_PASS","value":"$impleVat@123"},{"name":"SIMPLEVAT_SMTP_HOST","value":"smtp.gmail.com"},{"name":"SIMPLEVAT_SMTP_PORT","value":"587"},{"name":"SIMPLEVAT_SMTP_AUTH","value":"true"},{"name":"SIMPLEVAT_SMTP_STARTTLS_ENABLE","value":"true"},{"name":"SIMPLEVAT_ENVIRONMENT","value":"dev"},{"name":"SIMPLEVAT_SUBDOMAIN","value":"dev"},{"name":"SIMPLEVAT_TOKEN","value":"XXXX"},{"name":"SIMPLEVAT_RELEASE","value":"0-0-2-beta-1-12"},{"name":"SIMPLEVAT_DB_HOST","value":"34.68.185.169"},{"name":"SIMPLEVAT_DB","value":"simplevat_db"},{"name":"SIMPLEVAT_DB_USER","value":"proxyuser"},{"name":"SIMPLEVAT_DB_PASSWORD","value":"SimpleVat123$"}],"image":"gcr.io/simplevat-dev/simplevat:0-0-2-beta-1-12","name":"simplevat","ports":[{"containerPort":8080}],"readinessProbe":{"failureThreshold":10,"httpGet":{"path":"/healthz/index.html","port":8080},"periodSeconds":1,"successThreshold":1,"timeoutSeconds":1}}]}}}}
    creationTimestamp: "2019-09-28T09:26:42Z"
    generation: 1
    labels:
      app: simplevat
    name: simplevat-rc-dev-0-0-2-beta-1-13
    namespace: simplevat-dev
    resourceVersion: "378476"
    selfLink: /api/v1/namespaces/simplevat-dev/replicationcontrollers/simplevat-rc-dev-0-0-2-beta-1-13
    uid: 151a61ca-e1d2-11e9-9c64-42010a8001b7
  spec:
    replicas: 3
    selector:
      app: simplevat
      deployment: 4eb9c60716c5393aaa5eff2da5075a03
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: simplevat
          deployment: 4eb9c60716c5393aaa5eff2da5075a03
      spec:
        containers:
        - env:
          - name: SIMPLEVAT_SMTP_USER
            value: support@simplevat.com
          - name: SIMPLEVAT_SMTP_PASS
            value: $impleVat@123
          - name: SIMPLEVAT_SMTP_HOST
            value: smtp.gmail.com
          - name: SIMPLEVAT_SMTP_PORT
            value: "587"
          - name: SIMPLEVAT_SMTP_AUTH
            value: "true"
          - name: SIMPLEVAT_SMTP_STARTTLS_ENABLE
            value: "true"
          - name: SIMPLEVAT_ENVIRONMENT
            value: dev
          - name: SIMPLEVAT_SUBDOMAIN
            value: dev
          - name: SIMPLEVAT_TOKEN
            value: XXXX
          - name: SIMPLEVAT_RELEASE
            value: 0-0-2-beta-1-12
          - name: SIMPLEVAT_DB_HOST
            value: 34.68.185.169
          - name: SIMPLEVAT_DB
            value: simplevat_db
          - name: SIMPLEVAT_DB_USER
            value: proxyuser
          - name: SIMPLEVAT_DB_PASSWORD
            value: SimpleVat123$
          image: gcr.io/simplevat-dev/simplevat:0-0-2-beta-1-12
          imagePullPolicy: IfNotPresent
          name: simplevat
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthz/index.html
              port: 8080
              scheme: HTTP
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    fullyLabeledReplicas: 3
    observedGeneration: 1
    readyReplicas: 3
    replicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
