apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-db-credentials-datainn
  namespace: simplevat-app
type: Opaque
data:
  username: c3ZfZGF0YWlubl9hcHBfZGJfdXNlcg==
  password: M0ZUenliMDdHV0Nk
  database: c3ZfZGF0YWlubl9hcHBfZGI=
