export const COMMON = {
	START_LOADING: 'START_LOADING',
	END_LOADING: 'END_LOADING',
	VAT_VERSION: 'VAT_VERSION',
	TOSTIFY_ALERT_FUNC: 'TOSTIFY_ALERT_FUNC',
	TOSTIFY_ALERT: 'TOSTIFY_ALERT',
	CURRENCY_LIST: 'CURRENCY_LIST',
	UNIVERSAL_CURRENCY_LIST: 'UNIVERSAL_CURRENCY_LIST',
	USER_ROLE_LIST: 'USER_ROLE_LIST',
	COMPANY_PROFILE: 'COMPANY_PROFILE',
};

export const EMPLOYEE ={

};

export const AUTH = {
	SIGNED_IN: 'SIGNED_IN',
	SIGNED_OUT: 'SIGNED_OUT',
	USER_PROFILE: 'USER_PROFILE',
	REGISTER: 'REGISTER',
};

export const TEMP = {
	CUSTOMER_INVOICE_REPORT: 'CUSTOMER_INVOICE_REPORT',
	CONTACT_LIST: 'CONTACT_LIST',
	ACCOUNT_BALANCE_REPORT: 'ACCOUNT_BALANCE_REPORT',
	ACCOUNT_TYPE_LIST: 'ACCOUNT_TYPE_LIST',
	TRANSACTION_TYPE_LIST: 'TRANSACTION_TYPE_LIST',
	TRANSACTION_CATEGORY_LIST: 'TRANSACTION_CATEGORY_LIST',
};

export const DASHBOARD = {
	BANK_ACCOUNT_TYPE: 'BANK_ACCOUNT_TYPE',
	BANK_ACCOUNT_GRAPH: 'BANK_ACCOUNT_GRAPH',
	CASH_FLOW_GRAPH: 'CASH_FLOW_GRAPH',
	INVOICE_GRAPH: 'INVOICE_GRAPH',
	PROFIT_LOSS: 'PROFIT_LOSS',
	TAXES: 'TAXES',
	EXPENSE_GRAPH: 'EXPENSE_GRAPH',
	REVENUE_GRAPH: 'REVENUE_GRAPH',
};

export const BANK_ACCOUNT = {
	BANK_ACCOUNT_LIST: 'BANK_ACCOUNT_LIST',
	BANK_TRANSACTION_LIST: 'BANK_TRANSACTION_LIST',
	ACCOUNT_TYPE_LIST: 'ACCOUNT_TYPE_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
	TRANSACTION_CATEGORY_LIST: 'TRANSACTION_CATEGORY_LIST',
	TRANSACTION_TYPE_LIST: 'TRANSACTION_TYPE_LIST',
	PROJECT_LIST: 'PROJECT_LIST',
	CUSTOMER_INVOICE_LIST: 'CUSTOMER_INVOICE_LIST',
	VENDOR_INVOICE_LIST: 'VENDOR_INVOICE_LIST',
	EXPENSE_LIST: 'EXPENSE_LIST',
	EXPENSE_CATEGORIES_LIST: 'EXPENSE_CATEGORIES_LIST',
	USER_LIST: 'USER_LIST',
	VENDOR_LIST: 'VENDOR_LIST',
	VAT_LIST: 'VAT_LIST',
	RECONCILE_LIST: 'RECONCILE_LIST',
	UNPAID_PAYROLLS:"UNPAID_PAYROLLS",
};



export const CONTACT = {
	CONTACT_LIST: 'CONTACT_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
	CONTACT_TYPE_LIST: 'CONTACT_TYPE_LIST',
	STATE_LIST: 'STATE_LIST',
};
export const EMPLOYEEPAYROLL = {
	// EMPLOYEE_LIST_SUMMURY: 'EMPLOYEE_LIST_SUMMURY',
	PAYROLL_EMPLOYEE_LIST: 'PAYROLL_EMPLOYEE_LIST',
	APPROVER_DROPDOWN:'APPROVER_DROPDOWN',
	USER_APPROVER_GENERATER_DROPDOWN: 'USER_APPROVER_GENERATER_DROPDOWN',
	INCOMPLETED_EMPLOYEE_LIST: 'INCOMPLETED_EMPLOYEE_LIST',
	// CURRENCY_LIST:'CURRENCY_LIST',
	 COUNTRY_LIST:'COUNTRY_LIST',
	 STATE_LIST: 'STATE_LIST',
	 SALARY_STRUCTURE_DROPDOWN: 'SALARY_STRUCTURE_DROPDOWN',
	DESIGNATION_DROPDOWN: 'DESIGNATION_DROPDOWN',
    EMPLOYEE_LIST_DDROPDOWN: 'EMPLOYEE_LIST_DDROPDOWN',
    SALARY_ROLE_DROPDOWN : 'SALARY_ROLE_DROPDOWN',
	SALARY_COMPONENT_FIXED_DROPDOWN: "SALARY_COMPONENT_FIXED_DROPDOWN",
	SALARY_COMPONENT_VARAIBLE_DROPDOWN: "SALARY_COMPONENT_VARAIBLE_DROPDOWN",
	SALARY_COMPONENT_DEDUCTION_DROPDOWN: "SALARY_COMPONENT_DEDUCTION_DROPDOWN",
	PAYROLL_LIST: 'PAYROLL_LIST',
	
};
export const SALARY_ROLES = {
	SALARY_ROLES_LIST: 'SALARY_ROLES_LIST',
};
export const EMPLOYEE_DESIGNATION = {
	EMPLOYEE_DESIGNATION_LIST : 'EMPLOYEE_DESIGNATION_LIST'
	
};
export const SALARY_STRUCTURE = {
	SALARY_STRUCTURE_LIST: 'SALARY_STRUCTURE_LIST',
};
export const SALARY_TEMPLATE ={
	TEMPLATE_LIST: 'TEMPLATE_LIST',
	SALARY_STRUCTURE_DROPDOWN:'SALARY_STRUCTURE_DROPDOWN',
	SALARY_ROLE_DROPDOWN: 'SALARY_ROLE_DROPDOWN',

};


export const REPORTS ={
	SALES_BY_CUSTOMER: 'SALES_BY_CUSTOMER',
	SALES_BY_ITEM: 'SALES_BY_ITEM',
	PURCHASE_BY_VENDOR: 'PURCHASE_BY_VENDOR',
	PURCHASE_BY_ITEM: 'PURCHASE_BY_ITEM',
	COMPANY_PROFILE: 'COMPANY_PROFILE',
	RECEIVABLE_INVOICE: 'RECEIVABLE_INVOICE',
	PAYABLE_INVOICE: 'PAYABLE_INVOICE',
	CREDITNOTE_DETAILS : 'CREDITNOTE_DETAILS',

};

export const EXPENSE = {
	EXPENSE_LIST: 'EXPENSE_LIST',
	EXPENSE_DETAIL: 'EXPENSE_DETAIL',
	CURRENCY_LIST: 'CURRENCY_LIST',
	SUPPLIER_LIST: 'SUPPLIER_LIST',
	EMPLOYEE_LIST: 'EMPLOYEE_LIST',
	CUSTOMER_LIST: 'CUSTOMER_LIST',
	PROJECT_LIST: 'PROJECT_LIST',
	PAYMENT_LIST: 'PAYMENT_LIST',
	EXPENSE_CATEGORIES_LIST: 'EXPENSE_CATEGORIES_LIST',
	VAT_LIST: 'VAT_LIST',
	BANK_LIST: 'BANK_LIST',
	PAY_MODE: 'PAY_MODE',
	USER_LIST: 'USER_LIST',
	PAY_TO_LIST: 'PAY_TO_LIST',
};

export const REQUEST_FOR_QUOTATION = {
	REQUEST_FOR_QUOTATION_LIST: 'REQUEST_FOR_QUOTATION_LIST',
	PROJECT_LIST: 'PROJECT_LIST',
	CONTACT_LIST: 'CONTACT_LIST',
	STATUS_LIST: 'STATUS_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	VAT_LIST: 'VAT_LIST',
	PRODUCT_LIST: 'PRODUCT_LIST',
	SUPPLIER_LIST: 'SUPPLIER_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
	DEPOSIT_LIST: 'DEPOSIT_LIST',
	PAY_MODE: 'PAY_MODE',
	PLACE_OF_SUPPLY:'PLACE_OF_SUPPLY',

};

export const PURCHASE_ORDER ={
	PURCHASE_ORDER_LIST: 'PURCHASE_ORDER_LIST',
	PROJECT_LIST: 'PROJECT_LIST',
	CONTACT_LIST: 'CONTACT_LIST',
	STATUS_LIST: 'STATUS_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	VAT_LIST: 'VAT_LIST',
	PRODUCT_LIST: 'PRODUCT_LIST',
	SUPPLIER_LIST: 'SUPPLIER_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
	DEPOSIT_LIST: 'DEPOSIT_LIST',
	PAY_MODE: 'PAY_MODE',
	PLACE_OF_SUPPLY:'PLACE_OF_SUPPLY',
	RFQ_LIST:'RFQ_LIST',
};
export const GOODS_RECEVED_NOTE ={
	GOODS_RECEVED_NOTE_LIST: 'GOODS_RECEVED_NOTE_LIST',
	PROJECT_LIST: 'PROJECT_LIST',
	CONTACT_LIST: 'CONTACT_LIST',
	STATUS_LIST: 'STATUS_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	VAT_LIST: 'VAT_LIST',
	PRODUCT_LIST: 'PRODUCT_LIST',
	SUPPLIER_LIST: 'SUPPLIER_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
	DEPOSIT_LIST: 'DEPOSIT_LIST',
	PAY_MODE: 'PAY_MODE',
	PLACE_OF_SUPPLY:'PLACE_OF_SUPPLY',
	PO_LIST:'PO_LIST',
};
export const QUOTATION ={
	QUOTATION_LIST: 'QUOTATION_LIST',
	PROJECT_LIST: 'PROJECT_LIST',
	CONTACT_LIST: 'CONTACT_LIST',
	STATUS_LIST: 'STATUS_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	VAT_LIST: 'VAT_LIST',
	PRODUCT_LIST: 'PRODUCT_LIST',
	SUPPLIER_LIST: 'SUPPLIER_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
	DEPOSIT_LIST: 'DEPOSIT_LIST',
	PAY_MODE: 'PAY_MODE',
	PLACE_OF_SUPPLY:'PLACE_OF_SUPPLY',
};

export const SETTINGS = {};

export const CUSTOMER_INVOICE = {
	CUSTOMER_INVOICE_LIST: 'CUSTOMER_INVOICE_LIST',
	PROJECT_LIST: 'PROJECT_LIST',
	CUSTOMER_LIST: 'CUSTOMER_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	VAT_LIST: 'VAT_LIST',
	PRODUCT_LIST: 'PRODUCT_LIST',
	STATUS_LIST: 'STATUS_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
	DEPOSIT_LIST: 'DEPOSIT_LIST',
	PAY_MODE: 'PAY_MODE',
	PLACE_OF_SUPPLY: 'PLACE_OF_SUPPLY',
	INVOICE_LIST_FOR_DROPDOWN:"INVOICE_LIST_FOR_DROPDOWN",
};

export const SUPPLIER_INVOICE = {
	SUPPLIER_INVOICE_LIST: 'SUPPLIER_INVOICE_LIST',
	PROJECT_LIST: 'PROJECT_LIST',
	CONTACT_LIST: 'CONTACT_LIST',
	STATUS_LIST: 'STATUS_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	VAT_LIST: 'VAT_LIST',
	PRODUCT_LIST: 'PRODUCT_LIST',
	SUPPLIER_LIST: 'SUPPLIER_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
	DEPOSIT_LIST: 'DEPOSIT_LIST',
	PAY_MODE: 'PAY_MODE',
	PLACE_OF_SUPPLY:'PLACE_OF_SUPPLY',
};

export const RECEIPT = {
	RECEIPT_LIST: 'RECEIPT_LIST',
	CONTACT_LIST: 'CONTACT_LIST',
	INVOICE_LIST: 'INVOICE_LIST',
};

export const PRODUCT = {
	PRODUCT_LIST: 'PRODUCT_LIST',
	PRODUCT_WHARE_HOUSE: 'PRODUCT_WHARE_HOUSE',
	PRODUCT_VAT_CATEGORY: 'PRODUCT_VAT_CATEGORY',
	PRODUCT_CATEGORY: 'PRODUCT_CATEGORY',
	INVENTORY_LIST: 'INVENTORY_LIST',
	INVENTORY_HISTORY_LIST:'INVENTORY_HISTORY_LIST',
};

export const IMPORT={
	FILE_DATA_LIST:"FILE_DATA_LIST"
}

export const PROJECT = {
	PROJECT_LIST: 'PROJECT_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
	TITLE_LIST: 'TITLE_LIST',
	CONTACT_LIST: 'CONTACT_LIST',
};

export const INVENTORY = {
	SUMMARY_LIST: 'SUMMMARY_LIST',
};

export const PAYMENT = {
	PAYMENT_LIST: 'PAYMENT_LIST',
	BANK_LIST: 'BANK_LIST',
	SUPPLIER_LIST: 'SUPPLIER_LIST',
	INVOICE_LIST: 'INVOICE_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	PROJECT_LIST: 'PROJECT_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
};

export const TRANSACTION = {
	TRANSACTION_LIST: 'TRANSACTION_LIST',
	TRANSACTION_ROW: 'TRANSACTION_ROW',
	TRANSACTION_TYPES: 'TRANSACTION_TYPES',
	TRANSACTION_VAT_CATEGORIES: 'TRANSACTION_VAT_CATEGORIES',
	TRANSACTION_PARENT_CATRGORY_CODE_LIST:
		'TRANSACTION_PARENT_CATEGORY_CODE_LIST',
};

export const USER = {
	USER_LIST: 'USER_LIST',
	ROLE_LIST: 'ROLE_LIST',
	COMPANY_TYPE_LIST: 'COMPANY_TYPE_LIST',
	EMPLOYEE_LIST: 'EMPLOYEE_LIST',
	DESIGNATION_DROPDOWN: 'DESIGNATION_DROPDOWN'
};

export const VAT = {
	VAT_LIST: 'VAT_LIST',
	VAT_ROW: 'VAT_ROW',
};

export const CURRENCY = {
	CURRENCY_LIST: 'CURRENCY_LIST',
};

export const CURRENCYCONVERT = {
	CURRENCY_CONVERTION_LIST:'CURRENCY_CONVERTION_LIST',
	CURRENCY_CONVERT_LIST:'CURRENCY_CONVERT_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
};

export const DATA_BACKUP = {};

export const HELP = {};

export const NOTIFICATION = {};

export const TEMPLATE = {};

export const ORGANIZATION = {
	COUNTRY_LIST: 'COUNTRY_LIST',
	INDUSTRY_TYPE_LIST: 'INDUSTRY_TYPE_LIST',
};

export const USERS_ROLES = {
	USER_ROLE_LIST: 'USER_ROLE_LIST',
};

export const REPORTS_FILING = {};

export const VAT_TRANSACTIONS = {
	VAT_TRANSACTION_LIST: 'VAT_TRANSACTION_LIST',
};

export const CHART_ACCOUNT = {
	TRANSACTION_CATEGORY_LIST: 'TRANSACTION_CATEGORY_LIST',
	TRANSACTION_TYPES: 'TRANSACTION_TYPES',
	SUB_TRANSACTION_TYPES: 'SUB_TRANSACTION_TYPES',
};

export const OPENING_BALANCE = {
	TRANSACTION_CATEGORY_LIST: 'TRANSACTION_CATEGORY_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	OPENING_BALANCE_LIST: 'OPENING_BALANCE_LIST',
};

export const JOURNAL = {
	JOURNAL_LIST: 'JOURNAL_LIST',
	TRANSACTION_CATEGORY_LIST: 'TRANSACTION_CATEGORY_LIST',
	CONTACT_LIST: 'CONTACT_LIST',
	CURRENCY_LIST: 'CURRENCY_LIST',
	VAT_LIST: 'VAT_LIST',
	PAGE_NUM: 'PAGE_NUM',
	CANCEL_FLAG: 'CANCEL_FLAG'
};

export const PRODUCT_CATEGORY = {
	PRODUCT_CATEGORY_LIST: 'PRODUCT_CATEGORY_LIST',
};
export const PROFILE = {
	CURRENCY_LIST: 'CURRENCY_LIST',
	COUNTRY_LIST: 'COUNTRY_LIST',
	INDUSTRY_TYPE_LIST: 'INDUSTRY_TYPE_LIST',
	COMPANY_TYPE_LIST: 'COMPANY_TYPE_LIST',
	ROLE_LIST: 'ROLE_LIST',
	INVOICING_STATE_LIST: 'INVOICING_STATE_LIST',
	COMPANY_STATE_LIST: 'COMPANY_STATE_LIST',
};

export const IMPORT_TRANSACTION = {
	DATE_FORMAT_LIST: 'DATE_FORMAT_LIST',
};
