apiVersion: v1
kind: Service
metadata:
  name: {BACKEND-SERVICE-NAME}
  namespace: simplevat-{NAMESPACE-NAME}
  labels:
    app: {BACKEND-SERVICE-LABEL}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: {REPLICATION-CONTROLLER-NAME}
