apiVersion: v1
kind: ReplicationController
metadata:
  name: {REPLICATION-CONTROLLER-NAME}
  namespace: simplevat-{NAMESPACE-NAME}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {REPLICATION-CONTROLLER-LABEL}
    spec:
      containers:
        - name: {TOMCAT-CONTAINER-NAME}
          image: gcr.io/simplevat-cluster/simplevat:{RELEASE-TAG}
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz/index.html
              port: 8080
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          env:
            - name: SIMPLEVAT_RELEASE
              value: {RELEASE-TAG}
            - name: SIMPLEVAT_DB_HOST
              value: 127.0.0.1:3306
            - name: SIMPLEVAT_DB
              value: {SIMPLEVAT-DB-NAME}              
            # These secrets are required to start the pod.
            # [START cloudsql_secrets]
            - name: SIMPLEVAT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: SIMPLEVAT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            # [END cloudsql_secrets]
        # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=simplevat-cluster:us-central1:simplevat-dev=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
      # [END volumes]          
