apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test6-app-frontend
  annotations:
    cert-manager.io/clusterissuer: simpleaccounts-letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
      - test6-app.app.simpleaccounts.io
      secretName: wildcard-app-simpleaccounts-io-tls
  rules:
    - host: "test6-app.app.simpleaccounts.io"
      http:
        paths:
          - path: /hello-world-one/*
            pathType: Prefix
            backend:
              service:
                name: aks-helloworld-one
                port:
                  number: 80
