export const COMMON = {
  START_LOADING: 'START_LOADING',
  END_LOADING: 'END_LOADING',
  VAT_VERSION: 'VAT_VERSION',
  TOSTIFY_ALERT_FUNC: 'TOSTIFY_ALERT_FUNC',
  TOSTIFY_ALERT: 'TOSTIFY_ALERT'
}

export const AUTH = {
  SIGNED_IN: 'SIGNED_IN',
  SIGNED_OUT: 'SIGNED_OUT',
  USER_PROFILE: 'USER_PROFILE'
}

export const TEMP = {
  CUSTOMER_INVOICE_REPORT : 'CUSTOMER_INVOICE_REPORT',
  CONTACT_LIST : 'CONTACT_LIST',
  ACCOUNT_BALANCE_REPORT :'ACCOUNT_BALANCE_REPORT',
  ACCOUNT_TYPE_LIST : 'ACCOUNT_TYPE_LIST',
  TRANSACTION_TYPE_LIST : 'TRANSACTION_TYPE_LIST',
  TRANSACTION_CATEGORY_LIST : 'TRANSACTION_CATEGORY_LIST'
}

export const DASHBOARD = {
  BANK_ACCOUNT_TYPE: 'BANK_ACCOUNT_TYPE',
  BANK_ACCOUNT_GRAPH: 'BANK_ACCOUNT_GRAPH',
  CASH_FLOW_GRAPH: 'CASH_FLOW_GRAPH',
  INVOICE_GRAPH: 'INVOICE_GRAPH',
  PROFIT_LOSS: 'PROFIT_LOSS',
  TAXES: 'TAXES',
  EXPENSE_GRAPH: 'EXPENSE_GRAPH',
  REVENUE_GRAPH: 'REVENUE_GRAPH'
}

export const BANK_ACCOUNT = {
  BANK_ACCOUNT_LIST: 'BANK_ACCOUNT_LIST',
  BANK_TRANSACTION_LIST: 'BANK_TRANSACTION_LIST',
  ACCOUNT_TYPE_LIST: 'ACCOUNT_TYPE_LIST',
  CURRENCY_LIST: 'CURRENCY_LIST',
  COUNTRY_LIST: 'COUNTRY_LIST'
}

export const EMPLOYEE = {
  CURRENCY_LIST: 'CURRENCY_LIST',
}

export const CONTACT = {
  CONTACT_LIST: 'CONTACT_LIST',
  CURRENCY_LIST: 'CURRENCY_LIST',
  COUNTRY_LIST: 'COUNTRY_LIST',
  CONTACT_TYPE_LIST: 'CONTACT_TYPE_LIST'
}

export const EXPENSE = {
  EXPENSE_LIST: 'EXPENSE_LIST',
  EXPENSE_DETAIL: 'EXPENSE_DETAIL',
  CURRENCY_LIST: 'CURRENCY_LIST',
  SUPPLIER_LIST: 'SUPPLIER_LIST',
  BANK_ACCOUNT_LIST: 'BANK_ACCOUNT_LIST',
  CUSTOMER_LIST: 'CUSTOMER_LIST',
  PROJECT_LIST: 'PROJECT_LIST',
  PAYMENT_LIST: 'PAYMENT_LIST',
  CHART_OF_ACCOUNT_LIST: 'CHART_OF_ACCOUNT_LIST',
  VAT_LIST: 'VAT_LIST'
}

export const SETTINGS = {

}

export const CUSTOMER_INVOICE = {
  CUSTOMER_INVOICE_LIST: 'CUSTOMER_INVOICE_LIST',

}

export const SUPPLIER_INVOICE = {
  SUPPLIER_INVOICE_LIST: 'SUPPLIER_INVOICE_LIST',
  CURRENCY_LIST: 'CURRENCY_LIST',
  VAT_LIST: 'VAT_LIST',
  PRODUCT_LIST: 'PRODUCT_LIST',
}

export const RECEIPT = {
  RECEIPT_LIST: 'RECEIPT_LIST'
}

export const PRODUCT = {
  PRODUCT_LIST: 'PRODUCT_LIST',
  PRODUCT_WHARE_HOUSE: 'PRODUCT_WHARE_HOUSE',
  PRODUCT_VAT_CATEGORY: 'PRODUCT_VAT_CATEGORY',
  PRODUCT_PARENT: 'PRODUCT_PARENT'
}

export const PROJECT = {
  PROJECT_LIST: 'PROJECT_LIST',
  CURRENCY_LIST: 'CURRENCY_LIST',
  COUNTRY_LIST: 'COUNTRY_LIST',
  TITLE_LIST: 'TITLE_LIST',
  CONTACT_LIST: 'CONTACT_LIST'
}

export const PAYMENT = {
  PAYMENT_LIST: 'PAYMENT_LIST',
  BANK_LIST: 'BANK_LIST',
  SUPPLIER_LIST: 'SUPPLIER_LIST',
  INVOICE_LIST: 'INVOICE_LIST',
  CURRENCY_LIST: 'CURRENCY_LIST',
  PROJECT_LIST: 'PROJECT_LIST',
}

export const TRANSACTION = {
  TRANSACTION_LIST: 'TRANSACTION_LIST',
  TRANSACTION_ROW: 'TRANSACTION_ROW',
  TRANSACTION_TYPES: 'TRANSACTION_TYPES',
  TRANSACTION_VAT_CATEGORIES: 'TRANSACTION_VAT_CATEGORIES',
  TRANSACTION_PARENT_CATRGORY_CODE_LIST: 'TRANSACTION_PARENT_CATEGORY_CODE_LIST'
}

export const USER = {
  USER_LIST: 'USER_LIST'
}

export const VAT = {
  VAT_LIST: 'VAT_LIST',
  VAT_ROW: 'VAT_ROW'
}

export const CURRENCY = {

}

export const DATA_BACKUP = {

}

export const HELP = {

}

export const NOTIFICATION = {

}

export const ORGANIZATION = {

}

export const USERS_ROLES = {
  
}

export const REPORTS_FILING = {

}

export const VAT_TRANSACTIONS = {
  
}

export const CHART_ACCOUNT = {
  TRANSACTION_CATEGORY_LIST: 'TRANSACTION_CATEGORY_LIST',
  TRANSACTION_TYPES: 'TRANSACTION_TYPES',
}


export const BEGINING_BALANCE = {
  
}


export const JOURNAL = {
  JOURNAL_LIST: 'JOURNAL_LIST'
}
