--liquibase formatted sql
<!-- user below line on top of script to execute your sql script <author : version>
--changeset 22/10/2020 AFZAL KHAN:ddl-1
-->
--changeset 22/10/2020 ZAIN KHAN:ddl-1
CREATE TABLE ACTIVITY (
  ACTIVITY_ID int(11) NOT NULL,
  ACTIVITY_CODE varchar(255) DEFAULT NULL,
  FIELD_1 varchar(255) DEFAULT NULL,
  FIELD_2 varchar(255) DEFAULT NULL,
  FIELD_3 varchar(255) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  MODULE_CODE varchar(255) DEFAULT NULL,
  UPDATED_BY int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE BANK_ACCOUNT (
  BANK_ACCOUNT_ID int(11) NOT NULL,
  ACCOUNT_NUMBER varchar(255) DEFAULT NULL,
  BANK_ACCOUNT_NAME varchar(255) DEFAULT NULL,
  BANK_FEED_STATUS_CODE int(11) DEFAULT NULL,
  BANK_NAME varchar(255) DEFAULT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  CURRENT_BALANCE decimal(19,2) DEFAULT 0.00,
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  IFSC_CODE varchar(255) DEFAULT NULL,
  ISPRIMARY_ACCOUNT_FLAG bit(1) NOT NULL DEFAULT b'1',
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  OPENING_BALANCE decimal(19,2) DEFAULT 0.00,
  PERSONAL_CORPORATE_ACCOUNT_IND char(1) NOT NULL DEFAULT 'C',
  SWIFT_CODE varchar(255) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  BANK_ACCOUNT_CURRENCY_CODE int(11) DEFAULT NULL,
  BANK_ACCOUNT_STATUS_CODE int(11) DEFAULT NULL,
  BANK_ACCOUNT_TYPE_CODE int(11) DEFAULT NULL,
  BANK_COUNTRY_CODE int(11) DEFAULT NULL,
  TRANSACTION_CATEGORY_CODE int(11) DEFAULT NULL,
  OPENING_DATE datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE BANK_ACCOUNT_STATUS (
  BANK_ACCOUNT_STATUS_CODE int(11) NOT NULL,
  BANK_ACCOUNT_STATUS_DESCRIPTION varchar(255) DEFAULT NULL,
  BANK_ACCOUNT_STATUS_NAME varchar(255) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE BANK_ACCOUNT_TYPE (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  NAME varchar(255) NOT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE BANK_FEED_STATUS (
  BANK_FEED_STATUS_CODE int(11) NOT NULL,
  BANK_FEED_STATUS_DESCRIPTION varchar(255) DEFAULT NULL,
  BANK_FEED_STATUS_NAME varchar(255) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE CHART_OF_ACCOUNT (
  CHART_OF_ACCOUNT_ID int(11) NOT NULL,
  CHART_OF_ACCOUNT_CATEGORY_CODE varchar(255) DEFAULT NULL,
  CHART_OF_ACCOUNT_CODE varchar(255) NOT NULL,
  CHART_OF_ACCOUNT_DESCRIPTION varchar(255) DEFAULT NULL,
  CHART_OF_ACCOUNT_NAME varchar(255) NOT NULL,
  DEBIT_CREDIT_FLAG char(1) NOT NULL,
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  PARENT_CHART_OF_ACCOUNT_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE CHART_OF_ACCOUNT_CATEGORY (
  CHART_OF_ACCOUNT_CATEGORY_ID int(11) NOT NULL,
  CHART_OF_ACCOUNT_CATEGORY_CODE varchar(255) NOT NULL,
  CHART_OF_ACCOUNT_CATEGORY_DESCRIPTION varchar(255) DEFAULT NULL,
  CHART_OF_ACCOUNT_CATEGORY_NAME varchar(255) NOT NULL,
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  SELECT_FLAG char(1) NOT NULL DEFAULT 'N',
  PARENT_CHART_OF_ACCOUNT_CATEGORY_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE COAC_TRANSACTION_CATEGORY (
  ID int(11) NOT NULL,
  CHART_OF_ACCOUNT_CATEGORY_ID int(11) DEFAULT NULL,
  TRANSACTION_CATEGORY_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE COA_COA_CATEGORY (
  ID int(11) NOT NULL,
  CHART_OF_ACCOUNT_ID int(11) DEFAULT NULL,
  CHART_OF_ACCOUNT_CATEGORY_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE COMPANY (
  COMPANY_ID int(11) NOT NULL,
  COMPANY_ADDRESS_LINE1 varchar(255) DEFAULT NULL,
  COMPANY_ADDRESS_LINE2 varchar(255) DEFAULT NULL,
  COMPANY_ADDRESS_LINE3 varchar(255) DEFAULT NULL,
  COMPANY_CITY varchar(255) DEFAULT NULL,
  COMPANY_EXPENSE_BUDGET decimal(19,2) DEFAULT 0.00,
  COMPANY_LOGO longblob DEFAULT NULL,
  COMPNAY_NAME varchar(255) DEFAULT NULL,
  COMPANY_PO_BOX_NUMBER varchar(255) DEFAULT NULL,
  COMPANY_POST_ZIP_CODE varchar(255) DEFAULT NULL,
  COMPANY_REGISTRATION_NUMBER varchar(255) DEFAULT NULL,
  COMPANY_REVENUE_BUDGET decimal(19,2) DEFAULT 0.00,
  COMPANY_STATE_REGION varchar(255) DEFAULT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DATE_FORMAT varchar(255) DEFAULT NULL,
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  EMAIL_ADDRESS varchar(255) DEFAULT NULL,
  INVOICING_ADDRESS_LINE1 varchar(255) DEFAULT NULL,
  INVOICING_ADDRESS_LINE2 varchar(255) DEFAULT NULL,
  INVOICING_ADDRESS_LINE3 varchar(255) DEFAULT NULL,
  INVOICING_CITY varchar(255) DEFAULT NULL,
  INVOICING_PO_BOX_NUMBER varchar(255) DEFAULT NULL,
  INVOICING_POST_ZIP_CODE varchar(255) DEFAULT NULL,
  INVOICING_REFERENCE_PATTERN varchar(255) DEFAULT NULL,
  INVOICING_STATE_REGION varchar(255) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  PHONE_NUMBER varchar(255) DEFAULT NULL,
  VAT_NUMBER varchar(255) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  WEBSITE varchar(255) DEFAULT NULL,
  COMPANY_COUNTRY_CODE int(11) DEFAULT NULL,
  COMPANY_TYPE_CODE int(11) DEFAULT NULL,
  CURRENCY_CODE int(11) DEFAULT NULL,
  INDUSTRY_TYPE_CODE int(11) DEFAULT NULL,
  INVOICING_COUNTRY_CODE int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE COMPANY_TYPE (
  COMPANY_TYPE_CODE int(11) NOT NULL,
  COMPANY_TYPE_DESCRIPTION varchar(255) DEFAULT NULL,
  COMPANY_TYPE_NAME varchar(255) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CONFIGURATION (
  ID int(11) NOT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  NAME varchar(255) NOT NULL,
  VALUE varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CONTACT (
  CONTACT_ID int(11) NOT NULL,
  ADDRESS_LINE1 varchar(255) DEFAULT NULL,
  ADDRESS_LINE2 varchar(255) DEFAULT NULL,
  ADDRESS_LINE3 varchar(255) DEFAULT NULL,
  BILLING_EMAIL varchar(255) DEFAULT NULL,
  CITY varchar(255) DEFAULT NULL,
  CONTACT_TYPE int(11) DEFAULT NULL,
  CONTRACT_PO_NUMBER varchar(255) DEFAULT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  EMAIL varchar(255) DEFAULT NULL,
  FIRST_NAME varchar(255) DEFAULT NULL,
  LAST_NAME varchar(255) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  MIDDLE_NAME varchar(255) DEFAULT NULL,
  MOBILE_NUMBER varchar(255) DEFAULT NULL,
  ORGANIZATION varchar(255) DEFAULT NULL,
  PO_BOX_NUMBER varchar(255) DEFAULT NULL,
  POST_ZIP_CODE varchar(255) DEFAULT NULL,
  TELEPHONE varchar(255) DEFAULT NULL,
  VAT_REGISTRATION_NUMBER varchar(255) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  COUNTRY_CODE int(11) DEFAULT NULL,
  CURRENCY_CODE int(11) DEFAULT NULL,
  STATE_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CONVERTED_CURRENCY (
  CURRENCY_CONVERSION_ID bigint(20) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  CURRENCY_CODE int(11) DEFAULT NULL,
  CURRENCY_CODE_CONVERTED_TO int(11) DEFAULT NULL,
  EXCHANGE_RATE decimal(19,9) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE COUNTRY (
  COUNTRY_CODE int(11) NOT NULL,
  COUNTRY_DESCRIPTION varchar(255) DEFAULT NULL,
  COUNTRY_NAME varchar(255) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  ISO_ALPHA3_CODE varchar(3) DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  CURRENCY_CODE int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CURRENCY (
  CURRENCY_CODE int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  CURRENCY_DESCRIPTION varchar(255) DEFAULT NULL,
  CURRENCY_ISO_CODE varchar(3) DEFAULT NULL,
  CURRENCY_NAME varchar(255) NOT NULL,
  CURRENCY_SYMBOL varchar(255) DEFAULT NULL,
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CUSTOMER_INVOICE_RECEIPT (
  ID bigint(20) NOT NULL,
  DUE_AMOUNT decimal(19,2) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  PAID_AMOUNT decimal(19,2) NOT NULL,
  CUSTOMER_INVOICE_ID int(11) DEFAULT NULL,
  RECEIPT_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE DATE_FORMAT (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  format varchar(255) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE DOCUMENT_TEMPLATE (
  ID int(11) NOT NULL,
  NAME varchar(255) NOT NULL,
  TEMPLATE longblob NOT NULL,
  TYPE int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE EMPLOYEE (
  ID int(11) NOT NULL,
  BILLING_EMAIL varchar(255) DEFAULT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  DATE_OF_BIRTH datetime NOT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  FIRST_NAME varchar(255) DEFAULT NULL,
  LAST_NAME varchar(255) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  MIDDLE_NAME varchar(255) DEFAULT NULL,
  PASSWORD varchar(255) DEFAULT NULL,
  PO_BOX_NUMBER varchar(255) DEFAULT NULL,
  REFERENCE_CODE varchar(255) DEFAULT NULL,
  TITLE varchar(255) DEFAULT NULL,
  VAT_REGISTRATION_NO varchar(255) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  CURRENCY_CODE int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE EXPENSE (
  EXPENSE_ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  EXPENSE_AMOUNT decimal(19,2) DEFAULT 0.00,
  EXPENSE_DATE datetime DEFAULT NULL,
  EXPENSE_DESCRIPTION varchar(255) DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  PAY_MODE varchar(32) DEFAULT 'CASH',
  PAYEE varchar(255) DEFAULT NULL,
  RECEIPT_ATTACHMENT_DESCRIPTION varchar(255) DEFAULT NULL,
  RECEIPT_ATTACHMENT_FILE_NAME varchar(255) DEFAULT NULL,
  RECEIPT_ATTACHMENT_PATH varchar(255) DEFAULT NULL,
  RECEIPT_NUMBER varchar(20) DEFAULT NULL,
  STATUS int(11) DEFAULT 1,
  VERSION_NUMBER int(11) DEFAULT 1,
  BANK_ACCOUNT_ID int(11) DEFAULT NULL,
  CURRENCY_CODE int(11) DEFAULT NULL,
  EMPLOYEE_ID int(11) DEFAULT NULL,
  PROJECT_ID int(11) DEFAULT NULL,
  TRANSACTION_CATEGORY_CODE int(11) DEFAULT NULL,
  VAT_ID int(11) DEFAULT NULL,
  USER_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE EXPLANATION_STATUS (
  EXPLANATION_STATUS_CODE int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  EXPLANATION_STATUS_DESCRIPTION varchar(255) DEFAULT NULL,
  EXPLANATION_STATUS_NAME varchar(255) NOT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  RECONSILE_JOURNAL_ID int(11) DEFAULT NULL,
  REMANING_TO_EXLAIN_BALANCE decimal(19,2) NOT NULL DEFAULT 0.00,
  TRANSACTION_ID int(11) DEFAULT NULL,
  INVOICE_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE hibernate_sequences (
  sequence_name varchar(255) NOT NULL,
  next_val bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IMPORTED_DRAFT_TRANSACTON (
  IMPORTED_TRANSACTION_ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  IMPORTED_DEBIT_CREDIT_FLAG char(1) NOT NULL,
  IMPORTED_TRANSACTION_AMOUNT decimal(19,2) DEFAULT 0.00,
  IMPORTED_TRANSACTION_DATE datetime DEFAULT NULL,
  IMPORTED_TRANSACTION_DESCRIPTION varchar(255) DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  BANK_ACCOUNT_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE INDUSTRY_TYPE (
  INDUSTRY_TYPE_CODE int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  INDUSTRY_TYPE_DESCRIPTION varchar(255) DEFAULT NULL,
  INDUSTRY_TYPE_NAME varchar(255) NOT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE INVOICE (
  ID int(11) NOT NULL,
  CONTACT_PO_NUMBER varchar(255) DEFAULT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  DISCOUNT decimal(19,2) DEFAULT 0.00,
  DISCOUNT_PERCENTAGE double DEFAULT 0,
  DISCOUNT_TYPE varchar(255) DEFAULT NULL,
  FREEZE bit(1) NOT NULL DEFAULT b'0',
  INVOICE_DATE datetime DEFAULT NULL,
  INVOICE_DUE_DATE datetime DEFAULT NULL,
  INVOICE_DUE_PERIOD varchar(255) DEFAULT 'NET_7',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  NOTES varchar(255) DEFAULT NULL,
  RECEIPT_ATTACHMENT_DESCRIPTION varchar(255) DEFAULT NULL,
  RECEIPT_ATTACHMENT_FILE_NAME varchar(255) DEFAULT NULL,
  RECEIPT_ATTACHMENT_PATH varchar(255) DEFAULT NULL,
  RECEIPT_NUMBER varchar(20) DEFAULT NULL,
  REFERENCE_NUMBER varchar(255) DEFAULT NULL,
  STATUS int(11) DEFAULT NULL,
  TAX_IDENTIFICATION_NUMBER varchar(255) DEFAULT NULL,
  TOTAL_AMOUNT decimal(19,2) DEFAULT 0.00,
  TOTAL_VAT_AMOUNT decimal(19,2) DEFAULT 0.00,
  TYPE int(11) NOT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  CONTACT_ID int(11) DEFAULT NULL,
  CURRENCY_CODE int(11) DEFAULT NULL,
  DOCUMENT_TEMPLATE_ID int(11) DEFAULT NULL,
  PROJECT_ID int(11) DEFAULT NULL,
  DUE_AMOUNT decimal(19,2) DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE INVOICE_LINE_ITEM (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  DESCRIPTION varchar(255) DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  QUANTITY int(11) NOT NULL,
  SUB_TOTAL decimal(19,2) DEFAULT 0.00,
  UNIT_PRICE decimal(19,2) DEFAULT 0.00,
  VERSION_NUMBER int(11) DEFAULT 1,
  INVOICE_ID int(11) DEFAULT NULL,
  VAT_ID int(11) DEFAULT NULL,
  PRODUCT_ID int(11) DEFAULT NULL,
  TRANSACTION_CATEGORY_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE JOURNAL (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  DESCRIPTION varchar(255) DEFAULT NULL,
  JOURNAL_DATE datetime DEFAULT NULL,
  JOURNAL_REFERENCE_NO varchar(255) DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  REFERENCE_TYPE varchar(255) NOT NULL,
  SUB_TOTAL_CREDIT_AMOUNT decimal(19,2) DEFAULT 0.00,
  SUB_TOTAL_DEBIT_AMOUNT decimal(19,2) DEFAULT 0.00,
  TOTAL_CREDIT_AMOUNT decimal(19,2) DEFAULT 0.00,
  TOTAL_DEBIT_AMOUNT decimal(19,2) DEFAULT 0.00,
  CURRENCY_ID int(11) DEFAULT NULL,
  RECONSILE_JOURNAL_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE JOURNAL_LINE_ITEM (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  CREDIT_AMOUNT decimal(19,2) DEFAULT NULL,
  DEBIT_AMOUNT decimal(19,2) DEFAULT NULL,
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  DESCRIPTION varchar(255) DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  REFERENCE_ID int(11) NOT NULL,
  REFERENCE_TYPE varchar(255) NOT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  CONTACT int(11) DEFAULT NULL,
  JOURNAL_ID int(11) DEFAULT NULL,
  TRANSACTION_CATEGORY int(11) DEFAULT NULL,
  VAT_CATEGORY int(11) DEFAULT NULL,
  CURRENT_BALANCE decimal(19,2) NOT NULL DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE LANGUAGE (
  LANGUAGE_CODE int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LANGUAGE_DESCRIPTION varchar(255) DEFAULT NULL,
  LANGUAGE_NAME varchar(255) NOT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE LEADGER_ENTRY (
  id bigint(20) NOT NULL,
  amount double DEFAULT NULL,
  balance double DEFAULT NULL,
  created_by bigint(20) DEFAULT NULL,
  created_time datetime DEFAULT NULL,
  note varchar(255) DEFAULT NULL,
  type varchar(255) DEFAULT NULL,
  updated_by bigint(20) DEFAULT NULL,
  updated_time datetime DEFAULT NULL,
  TRANSACTION_CATEGORY int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PATCH (
  ID int(11) NOT NULL,
  EXECUTION_DATE datetime NOT NULL,
  PATCH_NO varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PAYMENT (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  DESCRIPTION varchar(255) DEFAULT NULL,
  INVOICE_AMOUNT decimal(19,2) DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  PAYMENT_DATE datetime DEFAULT NULL,
  BANK_ID int(11) DEFAULT NULL,
  CURRENCY_CODE int(11) DEFAULT NULL,
  INVOICE_ID int(11) DEFAULT NULL,
  PROJECT_ID int(11) DEFAULT NULL,
  SUPPLIER_ID int(11) DEFAULT NULL,
  ATTACHMENT_DESCRIPTION varchar(255) DEFAULT NULL,
  ATTACHMENT_FILE_NAME varchar(255) DEFAULT NULL,
  ATTACHMENT_PATH varchar(255) DEFAULT NULL,
  NOTES varchar(255) DEFAULT NULL,
  PAY_MODE varchar(255) DEFAULT NULL,
  PAYMENT_NO varchar(255) DEFAULT NULL,
  REFERENCE_NO varchar(255) DEFAULT NULL,
  DEPOSITE_TO_TRANSACTION_CATEGORY_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCT (
  PRODUCT_ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) DEFAULT b'0',
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  PRODUCT_CODE varchar(255) DEFAULT NULL,
  PRODUCT_DESCRIPTION varchar(255) DEFAULT NULL,
  PRODUCT_NAME varchar(255) DEFAULT NULL,
  UNIT_PRICE decimal(19,2) DEFAULT NULL,
  VAT_INCLUDED bit(1) DEFAULT b'0',
  VERSION_NUMBER int(11) DEFAULT 1,
  PRODUCT_CATEGORY int(11) DEFAULT NULL,
  PRODUCT_WAREHOUSE int(11) DEFAULT NULL,
  PRODUCT_VAT int(11) DEFAULT NULL,
  PRICE_TYPE varchar(255) DEFAULT NULL,
  PRODUCT_TYPE varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCT_CATEGORY (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  PRODUCT_CATEGORY_CODE varchar(255) DEFAULT NULL,
  PRODUCT_CATEGORY_DESCRIPTION varchar(255) DEFAULT NULL,
  PRODUCT_CATEGORY_NAME varchar(255) NOT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCT_LINE_ITEM (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  DESCRIPTION varchar(255) DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  PRICE_TYPE varchar(255) DEFAULT NULL,
  UNIT_PRICE decimal(19,2) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  PRODUCT_ID int(11) DEFAULT NULL,
  TRANSACTION_CATEGORY_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PRODUCT_WAREHOUSE (
  WAREHOUSE_ID int(11) NOT NULL,
  DELETE_FLAG bit(1) DEFAULT b'0',
  VERSION_NUMBER int(11) DEFAULT 1,
  WAREHOUSE_NAME varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PROJECT (
  PROJECT_ID int(11) NOT NULL,
  CONTRACT_PO_NUMBER varchar(255) DEFAULT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  EXPENSE_BUDGET decimal(19,2) DEFAULT 0.00,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  PROJECT_NAME varchar(255) DEFAULT NULL,
  REVENUE_BUDGET decimal(19,2) DEFAULT 0.00,
  VAT_REGISTRATION_NUMBER varchar(255) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  CONTACT_ID int(11) DEFAULT NULL,
  CURRENCY_CODE int(11) DEFAULT NULL,
  LANGUAGE_CODE int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PURCHASE (
  PURCHASE_ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  PAYMENTMODE int(11) DEFAULT NULL,
  PURCHASE_AMOUNT decimal(19,2) DEFAULT 0.00,
  PURCHASE_DATE datetime DEFAULT NULL,
  PURCHASE_DESCRIPTION varchar(255) DEFAULT NULL,
  PURCHASE_DUE_AMOUNT decimal(19,2) DEFAULT 0.00,
  PURCHASE_DUE_DATE datetime DEFAULT NULL,
  PURCHASE_DUE_ON int(11) NOT NULL DEFAULT 0,
  RECEIPT_ATTACHMENT longblob DEFAULT NULL,
  RECEIPT_ATTACHMENT_DESCRIPTION varchar(255) DEFAULT NULL,
  RECEIPT_ATTACHMENT_PATH varchar(255) DEFAULT NULL,
  RECEIPT_NUMBER varchar(20) DEFAULT NULL,
  STATUS int(11) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  CURRENCY_CODE int(11) DEFAULT NULL,
  PROJECT_ID int(11) DEFAULT NULL,
  CONTACT_ID int(11) DEFAULT NULL,
  TRANSACTION_CATEGORY_CODE int(11) DEFAULT NULL,
  TRANSACTION_TYPE_CODE int(11) DEFAULT NULL,
  CLAIMANT_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PURCHASE_LINE_ITEM (
  PURCHASE_LINE_ITEM_ID int(11) NOT NULL,
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  PURCHASE_PRODUCT_NAME varchar(255) DEFAULT NULL,
  PURCHASE_LINE_ITEM_DESCRIPTION varchar(255) DEFAULT NULL,
  PURCHASE_LINE_ITEM_QUANTITY int(11) DEFAULT NULL,
  PURCHASE_LINE_ITEM_UNIT_PRICE decimal(19,2) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  PURCHASE_ID int(11) DEFAULT NULL,
  PURCHASE_LINE_ITEM_PRODUCT_ID int(11) DEFAULT NULL,
  PURCHASE_LINE_ITEM_VAT_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RECEIPT (
  ID int(11) NOT NULL,
  AMOUNT decimal(19,2) DEFAULT 0.00,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  RECEIPT_DATE datetime DEFAULT NULL,
  RECEIPT_NO varchar(255) DEFAULT NULL,
  REFERENCE_CODE varchar(255) DEFAULT NULL,
  CONTACT_ID int(11) DEFAULT NULL,
  INVOICE_ID int(11) DEFAULT NULL,
  NOTES varchar(255) DEFAULT NULL,
  PAY_MODE varchar(32) DEFAULT 'CASH',
  DEPOSITE_TO_TRANSACTION_CATEGORY_ID int(11) DEFAULT NULL,
  RECEIPT_ATTACHMENT_DESCRIPTION varchar(4000) DEFAULT NULL,
  RECEIPT_ATTACHMENT_FILE_NAME varchar(255) DEFAULT NULL,
  RECEIPT_ATTACHMENT_PATH varchar(1000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RECONCILESTATUS (
  RECONCILE_ID int(11) NOT NULL,
  BANK_ACCOUNT_ID int(11) DEFAULT NULL,
  RECONCILED_DATE datetime DEFAULT NULL,
  RECONCILED_DURATION varchar(255) DEFAULT NULL,
  CLOSING_BALANCE decimal(19,2) DEFAULT NULL,
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  RECONCILED_START_DATE datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RECONCILE_CATEGORY (
  ID int(11) NOT NULL,
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  RECONCILE_CATEGORY_CODE varchar(255) NOT NULL,
  RECONCILE_CATEGORY_DESCRIPTION varchar(255) DEFAULT NULL,
  RECONCILE_CATEGORY_NAME varchar(255) NOT NULL,
  PARENT_RECONCILE_CATEGORY_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ROLE (
  ROLE_CODE int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  ROLE_DESCRIPTION varchar(255) DEFAULT NULL,
  ROLE_NAME varchar(255) NOT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SEARCHVIEW (
  ID int(11) NOT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE STATE (
  STATE_ID int(11) NOT NULL,
  CREATED_BY int(11) DEFAULT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  STATE_NAME varchar(255) NOT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  COUNTRY_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SUPPLIER_INVOICE_PAYMENT (
  ID bigint(20) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  DUE_AMOUNT decimal(19,2) NOT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  PAID_AMOUNT decimal(19,2) NOT NULL,
  PAYMENT_ID int(11) DEFAULT NULL,
  SUPPLIER_INVOICE_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TAX_TRANSACTION (
  TAX_TRANSACTION_ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DUE_AMOUNT decimal(19,2) DEFAULT NULL,
  END_DATE date DEFAULT NULL,
  PAID_AMOUNT decimal(19,2) DEFAULT NULL,
  PAYMENT_DATE date DEFAULT NULL,
  START_DATE date DEFAULT NULL,
  STATUS int(11) DEFAULT NULL,
  VAT_IN decimal(19,2) DEFAULT NULL,
  VAT_OUT decimal(19,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TITLE (
  TITLE_CODE int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  TITLE_DESCRIPTION varchar(255) DEFAULT NULL,
  TITLE_NAME varchar(255) NOT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TRANSACTIONVIEW (
  TRANSACTION_ID int(11) NOT NULL,
  BANK_ACCOUNT_ID int(11) DEFAULT NULL,
  CONTACT_NAME varchar(255) DEFAULT NULL,
  CURRENCY_SYMBOL varchar(255) DEFAULT NULL,
  CURRENT_BALANCE decimal(19,2) DEFAULT NULL,
  DEBIT_CREDIT_FLAG char(1) DEFAULT NULL,
  DUE_AMOUNT decimal(19,2) DEFAULT NULL,
  DUE_ON datetime DEFAULT NULL,
  ENTRY_TYPE int(11) DEFAULT NULL,
  EXPLANATION_STATUS_CODE int(11) DEFAULT NULL,
  EXPLANATION_STATUS_NAME varchar(255) DEFAULT NULL,
  PARENT_TRANSACTION int(11) DEFAULT NULL,
  REFERENCE_ID int(11) DEFAULT NULL,
  REFERENCE_NAME varchar(255) DEFAULT NULL,
  REFERENCE_TYPE int(11) DEFAULT NULL,
  TRANSACTION_AMOUNT decimal(19,2) DEFAULT NULL,
  TRANSACTION_CATEGORY_NAME varchar(255) DEFAULT NULL,
  TRANSACTION_DATE datetime DEFAULT NULL,
  TRANSACTION_DESCRIPTION varchar(255) DEFAULT NULL,
  TRANSACTION_TYPE_NAME varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TRANSACTION_CATEGORY (
  TRANSACTION_CATEGORY_ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) NOT NULL DEFAULT 'N',
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  EDITABLE_FLAG bit(1) NOT NULL DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  SELECTABLE_FLAG bit(1) NOT NULL DEFAULT b'0',
  TRANSACTION_CATEGORY_CODE varchar(255) DEFAULT NULL,
  TRANSACTION_CATEGORY_DESCRIPTION varchar(255) DEFAULT NULL,
  TRANSACTION_CATEGORY_NAME varchar(255) NOT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  CHART_OF_ACCOUNT_ID int(11) DEFAULT NULL,
  PARENT_TRANSACTION_CATEGORY_CODE int(11) DEFAULT NULL,
  VAT_CATEGORY_CODE int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE TRANSACTION_CATEGORY_BALANCE (
  TRANSACTION_CATEGORY_BALANCE_ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  EFFECTIVE_DATE datetime NOT NULL DEFAULT current_timestamp(),
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  OPENING_BALANCE decimal(19,2) NOT NULL DEFAULT 0.00,
  RUNNING_BALANCE decimal(19,2) NOT NULL DEFAULT 0.00,
  TRANSACTION_CATEGORY_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TRANSACTION_CATEGORY_CLOSING_BALANCE (
  TRANSACTION_CATEGORY_CLOSING_BALANCE_ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  EFFECTIVE_DATE datetime NOT NULL DEFAULT current_timestamp(),
  TRANSACTION_CATEGORY_CLOSING_BALANCE_DATE datetime DEFAULT NULL,
  OPENING_BALANCE decimal(19,2) NOT NULL DEFAULT 0.00,
  CLOSING_BALANCE decimal(19,2) NOT NULL DEFAULT 0.00,
  TRANSACTION_CATEGORY_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TRANSACTION_DATA_COL_MAPPING (
  ID int(11) NOT NULL,
  COL_NAME varchar(255) DEFAULT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  FILE_COL_INDEX int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  DATE_FORMAT_ID int(11) DEFAULT NULL,
  TRANSACTION_DATA_COL_MAPPING_ID bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TRANSACTION_PARSING_SETTING (
  ID bigint(20) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  delimiter varchar(255) DEFAULT NULL,
  HEADER_ROW_NO int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  OTHER_DELIMITER varchar(255) DEFAULT NULL,
  SKIP_ROWS int(11) DEFAULT NULL,
  TEXT_QUALIFIER varchar(255) DEFAULT NULL,
  DATE_FORMAT_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TRANSACTON (
  TRANSACTION_ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  CURRENT_BALANCE decimal(19,2) NOT NULL DEFAULT 0.00,
  DEBIT_CREDIT_FLAG char(1) NOT NULL,
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  ENTRY_TYPE int(11) DEFAULT NULL,
  EXPLAINED_TRANSACTION_ATTACHEMENT longblob DEFAULT NULL,
  EXPLAINED_TRANSACTION_ATTACHEMENT_DESCRIPTION varchar(255) DEFAULT NULL,
  EXPLAINED_TRANSACTION_ATTACHEMENT_FILE_NAME varchar(255) DEFAULT NULL,
  EXPLAINED_TRANSACTION_ATTACHEMENT_PATH varchar(255) DEFAULT NULL,
  EXPLAINED_TRANSACTION_DESCRIPTION varchar(255) DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  RECEIPT_NUMBER varchar(255) DEFAULT NULL,
  REFERENCE_ID int(11) DEFAULT NULL,
  REFERENCE_TYPE int(11) DEFAULT NULL,
  TRANSACTION_AMOUNT decimal(19,2) DEFAULT 0.00,
  TRANSACTION_DATE datetime DEFAULT NULL,
  TRANSACTION_DESCRIPTION varchar(255) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  BANK_ACCOUNT_ID int(11) DEFAULT NULL,
  TRANSACTION_TYPE_CODE int(11) DEFAULT NULL,
  EXPLAINED_TRANSACTION_CATEGORY_CODE int(11) DEFAULT NULL,
  PARENT_TRANSACTION int(11) DEFAULT NULL,
  EXPLAINED_PROJECT_ID int(11) DEFAULT NULL,
  EXPLANATION_STATUS_CODE int(11) DEFAULT NULL,
  EXPLINTION_BANK_ACCOUNT_ID int(11) DEFAULT NULL,
  EXPLINTION_CUSTOMER_CONTACT_ID int(11) DEFAULT NULL,
  EXPLINTION_VENDOR_CONTACT_ID int(11) DEFAULT NULL,
  TRANSACTIN_CREATION_MODE varchar(32) DEFAULT 'MANUAL',
  TRANSACTIN_EXPLINATION_STATUS varchar(32) DEFAULT 'NOT_EXPLAIN',
  EXPLINTION_EMPLOYEE_ID int(11) DEFAULT NULL,
  VAT_ID int(11) DEFAULT NULL,
  REFERENCE_STR varchar(4000) DEFAULT NULL,
  COA_CATEGORY_ID int(11) DEFAULT NULL,
  EXPLINTION_USER_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TRANSACTON_EXPENSES (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime DEFAULT current_timestamp(),
  EXPLANATION_STATUS_NAME varchar(255) NOT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  REMANING_TO_EXLAIN_BALANCE decimal(19,2) NOT NULL DEFAULT 0.00,
  EXPENSE_ID int(11) DEFAULT NULL,
  TRANSACTION_ID int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TRANSACTON_INVOICES (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime DEFAULT current_timestamp(),
  EXPLANATION_STATUS_NAME varchar(255) NOT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  REMANING_TO_EXLAIN_BALANCE decimal(19,2) NOT NULL DEFAULT 0.00,
  INVOICE_ID int(11) DEFAULT NULL,
  TRANSACTION_ID int(11) DEFAULT NULL,
  INVOICE_TYPE int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE USER (
  USER_ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DATE_OF_BIRTH datetime DEFAULT NULL,
  DELETE_FLAG bit(1) NOT NULL DEFAULT b'0',
  FIRST_NAME varchar(255) DEFAULT NULL,
  FORGOT_PASS_TOKEN varchar(4000) DEFAULT NULL,
  FORGOT_PASSWORD_TOKEN_EXPIRY_DATE datetime DEFAULT NULL,
  IS_ACTIVE bit(1) NOT NULL DEFAULT b'0',
  LAST_NAME varchar(255) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  USER_PASSWORD varchar(255) NOT NULL,
  PROFILE_IMAGE longblob DEFAULT NULL,
  USER_EMAIL varchar(255) NOT NULL,
  VERSION_NUMBER int(11) DEFAULT 1,
  COMPANY_ID int(11) DEFAULT NULL,
  EMPLOYEE_ID int(11) DEFAULT NULL,
  ROLE_CODE int(11) DEFAULT NULL,
  USER_TIMEZONE varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE VAT_CATEGORY (
  ID int(11) NOT NULL,
  CREATED_BY int(11) NOT NULL,
  CREATED_DATE datetime NOT NULL DEFAULT current_timestamp(),
  DEFAULT_FLAG char(1) DEFAULT 'N',
  DELETE_FLAG bit(1) DEFAULT b'0',
  LAST_UPDATED_BY int(11) DEFAULT NULL,
  LAST_UPDATE_DATE datetime DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  ORDER_SEQUENCE int(11) DEFAULT NULL,
  VAT decimal(19,2) DEFAULT NULL,
  VERSION_NUMBER int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ACTIVITY
  ADD PRIMARY KEY (ACTIVITY_ID);

ALTER TABLE BANK_ACCOUNT
  ADD PRIMARY KEY (BANK_ACCOUNT_ID),
  ADD KEY FK7gyvf96engpkstnlx0km25hnx (BANK_ACCOUNT_TYPE_CODE),
  ADD KEY FKg5ulpraj00tfm93e8e9wgqg0d (TRANSACTION_CATEGORY_CODE),
  ADD KEY FKjbtrsxkijg3lycudidek73gas (BANK_ACCOUNT_STATUS_CODE),
  ADD KEY FKsqkl4hip9t6so1hvmkg4r66sb (BANK_COUNTRY_CODE),
  ADD KEY FKt79qvqsjwfddsrkw3gvguuhd2 (BANK_ACCOUNT_CURRENCY_CODE);

ALTER TABLE BANK_ACCOUNT_STATUS
  ADD PRIMARY KEY (BANK_ACCOUNT_STATUS_CODE);

ALTER TABLE BANK_ACCOUNT_TYPE
  ADD PRIMARY KEY (ID);

ALTER TABLE BANK_FEED_STATUS
  ADD PRIMARY KEY (BANK_FEED_STATUS_CODE);

ALTER TABLE CHART_OF_ACCOUNT
  ADD PRIMARY KEY (CHART_OF_ACCOUNT_ID),
  ADD KEY FKre1ysibn9nq0k8de4po3vx532 (PARENT_CHART_OF_ACCOUNT_ID);

ALTER TABLE CHART_OF_ACCOUNT_CATEGORY
  ADD PRIMARY KEY (CHART_OF_ACCOUNT_CATEGORY_ID),
  ADD KEY FKbxq8eqi3d1bqur3qgjrw9c8dd (PARENT_CHART_OF_ACCOUNT_CATEGORY_ID);

ALTER TABLE COAC_TRANSACTION_CATEGORY
  ADD PRIMARY KEY (ID),
  ADD KEY FKjtvaf2qkbfxmqoy1uhow42gej (CHART_OF_ACCOUNT_CATEGORY_ID),
  ADD KEY FKotkxrvw47bcol6wbtlfn9j4kd (TRANSACTION_CATEGORY_ID);

ALTER TABLE COA_COA_CATEGORY
  ADD PRIMARY KEY (ID),
  ADD KEY FK5nruai6t6flgrjfjv9dfnaru5 (CHART_OF_ACCOUNT_CATEGORY_ID),
  ADD KEY FK7fj2lusnqcaj66ax8gjfcxf59 (CHART_OF_ACCOUNT_ID);

ALTER TABLE COMPANY
  ADD PRIMARY KEY (COMPANY_ID),
  ADD KEY FK5v56uyx5n3yqgp1oihb0yhj3n (CURRENCY_CODE),
  ADD KEY FKbg6xkc6pgeldfwhk39xm3fwvm (INVOICING_COUNTRY_CODE),
  ADD KEY FKfg5i2mio7279ck8xsmo6q52qg (COMPANY_COUNTRY_CODE),
  ADD KEY FKnqq74rxx13yescw08lxq7qely (COMPANY_TYPE_CODE),
  ADD KEY FKp8uoqhxahoirfycrtlkx3jbek (INDUSTRY_TYPE_CODE);

ALTER TABLE COMPANY_TYPE
  ADD PRIMARY KEY (COMPANY_TYPE_CODE);

ALTER TABLE CONFIGURATION
  ADD PRIMARY KEY (ID);

ALTER TABLE CONTACT
  ADD PRIMARY KEY (CONTACT_ID),
  ADD KEY FK36l0okantgoy213p9k62m4gxd (COUNTRY_CODE),
  ADD KEY FK9leffbmaeuqf01qi4k9tli7t1 (CURRENCY_CODE),
  ADD KEY FKrvoavc583kticwfy5xoioytqf (STATE_ID);

ALTER TABLE CONVERTED_CURRENCY
  ADD PRIMARY KEY (CURRENCY_CONVERSION_ID);

ALTER TABLE COUNTRY
  ADD PRIMARY KEY (COUNTRY_CODE),
  ADD KEY FK3y7owjhdlh9raaerjolmremxq (CURRENCY_CODE);

ALTER TABLE CURRENCY
  ADD PRIMARY KEY (CURRENCY_CODE);

ALTER TABLE CUSTOMER_INVOICE_RECEIPT
  ADD PRIMARY KEY (ID),
  ADD KEY FK1w519064bksnojirx1fddlups (CUSTOMER_INVOICE_ID),
  ADD KEY FK1t89wcd8sy641i8a53b2bcrf1 (RECEIPT_ID);

ALTER TABLE DATE_FORMAT
  ADD PRIMARY KEY (ID);

ALTER TABLE DOCUMENT_TEMPLATE
  ADD PRIMARY KEY (ID);

ALTER TABLE EMPLOYEE
  ADD PRIMARY KEY (ID),
  ADD KEY FK10udip6rb915p044ax50gtemn (CURRENCY_CODE);

ALTER TABLE EXPENSE
  ADD PRIMARY KEY (EXPENSE_ID),
  ADD KEY FK1h4m0sxriyj8h9y9mv5wqgsah (PROJECT_ID),
  ADD KEY FK6ape53fdcjqaoh9mgkm5tjeow (TRANSACTION_CATEGORY_CODE),
  ADD KEY FK833rj6bfe5fs104novi50dj08 (VAT_ID),
  ADD KEY FK8o9jahxc8ff8whom01rns88w8 (CURRENCY_CODE),
  ADD KEY FK8oasudvy4e86biit7kxxitdfd (BANK_ACCOUNT_ID),
  ADD KEY FKem8s6ne2t5amugd8vwyru9a10 (EMPLOYEE_ID);

ALTER TABLE EXPLANATION_STATUS
  ADD PRIMARY KEY (EXPLANATION_STATUS_CODE),
  ADD KEY FKkj46hmgdeim6nqbsk4uujt0ql (RECONSILE_JOURNAL_ID),
  ADD KEY FKqieicwxm9x7q9vs1mcqve5tgu (TRANSACTION_ID),
  ADD KEY FKsbltb842k4hgrmpcg6a66oywp (INVOICE_ID);

ALTER TABLE hibernate_sequences
  ADD PRIMARY KEY (sequence_name);

ALTER TABLE IMPORTED_DRAFT_TRANSACTON
  ADD PRIMARY KEY (IMPORTED_TRANSACTION_ID),
  ADD KEY FKhlqsar5v2ll8dilawrltf5k8d (BANK_ACCOUNT_ID);

ALTER TABLE INDUSTRY_TYPE
  ADD PRIMARY KEY (INDUSTRY_TYPE_CODE);

ALTER TABLE INVOICE
  ADD PRIMARY KEY (ID),
  ADD KEY FKaclrvrkqd1ijj7hoyswu47ltk (DOCUMENT_TEMPLATE_ID),
  ADD KEY FKi0v8e8yn1e6u81x56egmsns5h (CONTACT_ID),
  ADD KEY FKjdl5oc2mqtx4wux9blw0beyst (PROJECT_ID),
  ADD KEY FKlxgj2wewrvmp53hp4s25khm7y (CURRENCY_CODE);

ALTER TABLE INVOICE_LINE_ITEM
  ADD PRIMARY KEY (ID),
  ADD KEY FK3us8ikqirbfv33g8stdxpkufi (INVOICE_ID),
  ADD KEY FKpwx0oqq7k62wy90jsoae397si (VAT_ID),
  ADD KEY FK1vtja97apxmby178xm9a7p5ot (PRODUCT_ID),
  ADD KEY FKoo2qdo7l6ijg1r06ph5u4g29w (TRANSACTION_CATEGORY_ID);

ALTER TABLE JOURNAL
  ADD PRIMARY KEY (ID),
  ADD KEY FKntbalkvf4pf72ok9scg0wybqu (CURRENCY_ID),
  ADD KEY FK8fofiubaq7ywt9mhhuhirnaut (RECONSILE_JOURNAL_ID);

ALTER TABLE JOURNAL_LINE_ITEM
  ADD PRIMARY KEY (ID),
  ADD KEY FK3nvxtauc7k1f22r909vwvit0j (VAT_CATEGORY),
  ADD KEY FK897i7s6k2ftgwr3y0tbleqmsw (JOURNAL_ID),
  ADD KEY FKl512nlsls7necq7n9lw8ly6wb (CONTACT),
  ADD KEY FKm7q0sr3jlg0nn62ty2n6d1sd (TRANSACTION_CATEGORY);

ALTER TABLE LANGUAGE
  ADD PRIMARY KEY (LANGUAGE_CODE);

ALTER TABLE LEADGER_ENTRY
  ADD PRIMARY KEY (id),
  ADD KEY FKot3b2pdxulwdl86x0d8t46olv (TRANSACTION_CATEGORY);

ALTER TABLE PATCH
  ADD PRIMARY KEY (ID);

ALTER TABLE PAYMENT
  ADD PRIMARY KEY (ID),
  ADD KEY FK1xc4pqahlfvai3uqnjdxro2cg (INVOICE_ID),
  ADD KEY FKde11t0tvotbsq3fyvyqoeakem (BANK_ID),
  ADD KEY FKej5ukmej5ganhkov18p08dbv0 (SUPPLIER_ID),
  ADD KEY FKhfkwm4145f62l0p7hevx9pkfh (PROJECT_ID),
  ADD KEY FKmyfaof47mpq1xt4oka050ia1v (CURRENCY_CODE),
  ADD KEY FK477s0wc9n8l6oupyoqk4v2g3c (DEPOSITE_TO_TRANSACTION_CATEGORY_ID);

ALTER TABLE PRODUCT
  ADD PRIMARY KEY (PRODUCT_ID),
  ADD KEY FKb1fvg8k36s1hkw7bph4xdicwb (PRODUCT_CATEGORY),
  ADD KEY FKdtukqv2nkx3ql9dn175w3m5vi (PRODUCT_VAT),
  ADD KEY FKgke93hg6nxjv8sphh2cgay1l7 (PRODUCT_WAREHOUSE);

ALTER TABLE PRODUCT_CATEGORY
  ADD PRIMARY KEY (ID);

ALTER TABLE PRODUCT_LINE_ITEM
  ADD PRIMARY KEY (ID),
  ADD KEY FKax4sf8pl7n9tgbl8dbonlyq9s (PRODUCT_ID),
  ADD KEY FK49pfehurx3mnt3ut4gygv57pp (TRANSACTION_CATEGORY_ID);

ALTER TABLE PRODUCT_WAREHOUSE
  ADD PRIMARY KEY (WAREHOUSE_ID);

ALTER TABLE PROJECT
  ADD PRIMARY KEY (PROJECT_ID),
  ADD KEY FKonsoyqqfrc36bnhs9v2jrn2m6 (CONTACT_ID),
  ADD KEY FKsl1b7xwfoip3qaaxqxou4k59m (LANGUAGE_CODE),
  ADD KEY FKsystjmngpibcub97hnelxglb5 (CURRENCY_CODE);

ALTER TABLE PURCHASE
  ADD PRIMARY KEY (PURCHASE_ID),
  ADD KEY FK688w41idqte3v1x4xxd7cuh7o (TRANSACTION_CATEGORY_CODE),
  ADD KEY FK8xoirx9xofqpeg9d0ym4l3wfc (CONTACT_ID),
  ADD KEY FKero9wumttdv7rigt7b3otunr6 (PROJECT_ID),
  ADD KEY FKquuc99nspry8dd9sqhrn9ck3w (CLAIMANT_ID),
  ADD KEY FKsaceh3lwoomi56ieeqncrl42d (TRANSACTION_TYPE_CODE),
  ADD KEY FKsykk14n7iv1sspx7k3736e8w2 (CURRENCY_CODE);

ALTER TABLE PURCHASE_LINE_ITEM
  ADD PRIMARY KEY (PURCHASE_LINE_ITEM_ID),
  ADD KEY FK7kan4atehkdj1avwma5n4jsgj (PURCHASE_LINE_ITEM_VAT_ID),
  ADD KEY FK8g781cnubw1y3yey7l765dd9y (PURCHASE_ID),
  ADD KEY FKfqsooxudbgeyxrkm0d0sieeqf (PURCHASE_LINE_ITEM_PRODUCT_ID);

ALTER TABLE RECEIPT
  ADD PRIMARY KEY (ID),
  ADD KEY FK51n4ndnvkek113y3eo85rlvxh (INVOICE_ID),
  ADD KEY FKr1fvo9bhp9dxux6dc27bgjr9k (CONTACT_ID),
  ADD KEY FKkhhdki7s8y02tu4ufdutgr60u (DEPOSITE_TO_TRANSACTION_CATEGORY_ID);

ALTER TABLE RECONCILESTATUS
  ADD PRIMARY KEY (RECONCILE_ID);

ALTER TABLE RECONCILE_CATEGORY
  ADD PRIMARY KEY (ID),
  ADD KEY FKkvyqtaicn740d1w4caco178vm (PARENT_RECONCILE_CATEGORY_ID);

ALTER TABLE ROLE
  ADD PRIMARY KEY (ROLE_CODE);

ALTER TABLE SEARCHVIEW
  ADD PRIMARY KEY (ID);

ALTER TABLE STATE
  ADD PRIMARY KEY (STATE_ID),
  ADD KEY FKi312viy9ek534eyiruaad6ixf (COUNTRY_ID);

ALTER TABLE SUPPLIER_INVOICE_PAYMENT
  ADD PRIMARY KEY (ID),
  ADD KEY FKfex7pckbnnbh9bruwgjcy2spr (PAYMENT_ID),
  ADD KEY FK4ph4idew15w6smdgom59kbhxg (SUPPLIER_INVOICE_ID);

ALTER TABLE TAX_TRANSACTION
  ADD PRIMARY KEY (TAX_TRANSACTION_ID);

ALTER TABLE TITLE
  ADD PRIMARY KEY (TITLE_CODE);

ALTER TABLE TRANSACTIONVIEW
  ADD PRIMARY KEY (TRANSACTION_ID);

ALTER TABLE TRANSACTION_CATEGORY
  ADD PRIMARY KEY (TRANSACTION_CATEGORY_ID),
  ADD KEY FKlbbqyxeqlk21vxhiic461yy26 (CHART_OF_ACCOUNT_ID),
  ADD KEY FKlxx3gnpeg77g538j5gom3fubu (VAT_CATEGORY_CODE),
  ADD KEY FKqp7r3h1eoj9jl1n5rmt1pwnmj (PARENT_TRANSACTION_CATEGORY_CODE);

ALTER TABLE TRANSACTION_CATEGORY_BALANCE
  ADD PRIMARY KEY (TRANSACTION_CATEGORY_BALANCE_ID),
  ADD KEY FK79g3xavym27ekuyw995yqlvrd (TRANSACTION_CATEGORY_ID);

ALTER TABLE TRANSACTION_CATEGORY_CLOSING_BALANCE
  ADD PRIMARY KEY (TRANSACTION_CATEGORY_CLOSING_BALANCE_ID),
  ADD KEY FK79g3xavym27ekuyw995yqldrv (TRANSACTION_CATEGORY_ID);

ALTER TABLE TRANSACTION_DATA_COL_MAPPING
  ADD PRIMARY KEY (ID),
  ADD KEY FK31oyusni6lge51kccyw03g660 (DATE_FORMAT_ID),
  ADD KEY FKsg4bm2mrbu8m4vrf75392ussh (TRANSACTION_DATA_COL_MAPPING_ID);

ALTER TABLE TRANSACTION_PARSING_SETTING
  ADD PRIMARY KEY (ID),
  ADD KEY FKo8c5ktmgxtuh0pr167p4gm50n (DATE_FORMAT_ID);

ALTER TABLE TRANSACTON
  ADD PRIMARY KEY (TRANSACTION_ID),
  ADD KEY FK56rhnp6nd3nru4845o863vt6o (PARENT_TRANSACTION),
  ADD KEY FKf22amenxf45h7oldv5w8avvl2 (EXPLANATION_STATUS_CODE),
  ADD KEY FKf82fpo3aojpcvofvstb1f4i3e (EXPLAINED_PROJECT_ID),
  ADD KEY FKkmrn5djmwm30equrdipotnqmg (TRANSACTION_TYPE_CODE),
  ADD KEY FKnhy5qd2lutaoaq9858ss7odf4 (EXPLAINED_TRANSACTION_CATEGORY_CODE),
  ADD KEY FKs61ftx9ipvaoy4ya5fc55se90 (BANK_ACCOUNT_ID),
  ADD KEY FKinfcruhes0vn2l7aan90fw2xu (EXPLINTION_BANK_ACCOUNT_ID),
  ADD KEY FKn0ptk14chjd7sig1hce277m9a (EXPLINTION_CUSTOMER_CONTACT_ID),
  ADD KEY FK9bxc5njntwhpd9vdjb02pdc24 (EXPLINTION_VENDOR_CONTACT_ID),
  ADD KEY FK34ln1pxogaxkhp2ws2e8dq9my (EXPLINTION_EMPLOYEE_ID),
  ADD KEY FK1o99egk2prramm7j3qh4r52qx (VAT_ID),
  ADD KEY FK9kk6m5arfjny7gk7wraj0vkeo (COA_CATEGORY_ID);

ALTER TABLE TRANSACTON_EXPENSES
  ADD PRIMARY KEY (ID);

ALTER TABLE TRANSACTON_INVOICES
  ADD PRIMARY KEY (ID);

ALTER TABLE USER
  ADD PRIMARY KEY (USER_ID),
  ADD KEY FKdup5w9kutiunoewb3bf9w1u0w (COMPANY_ID),
  ADD KEY FKe4ndlf6wkwgphdwe7tbrift9u (EMPLOYEE_ID),
  ADD KEY FKkaa9gg6h8pjd26u4ejhxg2lp6 (ROLE_CODE);

ALTER TABLE VAT_CATEGORY
  ADD PRIMARY KEY (ID);

ALTER TABLE ACTIVITY
  MODIFY ACTIVITY_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE CHART_OF_ACCOUNT_CATEGORY
  MODIFY CHART_OF_ACCOUNT_CATEGORY_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE COAC_TRANSACTION_CATEGORY
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE COA_COA_CATEGORY
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE COMPANY
  MODIFY COMPANY_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE CONFIGURATION
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE CONVERTED_CURRENCY
  MODIFY CURRENCY_CONVERSION_ID bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE COUNTRY
  MODIFY COUNTRY_CODE int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE CURRENCY
  MODIFY CURRENCY_CODE int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE CUSTOMER_INVOICE_RECEIPT
  MODIFY ID bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE DATE_FORMAT
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE DOCUMENT_TEMPLATE
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE EXPLANATION_STATUS
  MODIFY EXPLANATION_STATUS_CODE int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE INVOICE_LINE_ITEM
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE JOURNAL
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE JOURNAL_LINE_ITEM
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE LEADGER_ENTRY
  MODIFY id bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE PATCH
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE PAYMENT
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE PRODUCT_CATEGORY
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE PRODUCT_LINE_ITEM
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE PURCHASE_LINE_ITEM
  MODIFY PURCHASE_LINE_ITEM_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE RECEIPT
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE SEARCHVIEW
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE STATE
  MODIFY STATE_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE SUPPLIER_INVOICE_PAYMENT
  MODIFY ID bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE TAX_TRANSACTION
  MODIFY TAX_TRANSACTION_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE TRANSACTION_CATEGORY
  MODIFY TRANSACTION_CATEGORY_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE TRANSACTION_CATEGORY_BALANCE
  MODIFY TRANSACTION_CATEGORY_BALANCE_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE TRANSACTION_CATEGORY_CLOSING_BALANCE
  MODIFY TRANSACTION_CATEGORY_CLOSING_BALANCE_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE TRANSACTION_DATA_COL_MAPPING
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE TRANSACTION_PARSING_SETTING
  MODIFY ID bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE TRANSACTON_EXPENSES
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE TRANSACTON_INVOICES
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE USER
  MODIFY USER_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE VAT_CATEGORY
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE BANK_ACCOUNT
  ADD CONSTRAINT FK7gyvf96engpkstnlx0km25hnx FOREIGN KEY (BANK_ACCOUNT_TYPE_CODE) REFERENCES BANK_ACCOUNT_TYPE (ID),
  ADD CONSTRAINT FKg5ulpraj00tfm93e8e9wgqg0d FOREIGN KEY (TRANSACTION_CATEGORY_CODE) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID),
  ADD CONSTRAINT FKjbtrsxkijg3lycudidek73gas FOREIGN KEY (BANK_ACCOUNT_STATUS_CODE) REFERENCES BANK_ACCOUNT_STATUS (BANK_ACCOUNT_STATUS_CODE),
  ADD CONSTRAINT FKsqkl4hip9t6so1hvmkg4r66sb FOREIGN KEY (BANK_COUNTRY_CODE) REFERENCES COUNTRY (COUNTRY_CODE),
  ADD CONSTRAINT FKt79qvqsjwfddsrkw3gvguuhd2 FOREIGN KEY (BANK_ACCOUNT_CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE);

ALTER TABLE CHART_OF_ACCOUNT
  ADD CONSTRAINT FKmv884viql8dw65tmuala2vtjw FOREIGN KEY (PARENT_CHART_OF_ACCOUNT_ID) REFERENCES CHART_OF_ACCOUNT (CHART_OF_ACCOUNT_ID),
  ADD CONSTRAINT FKre1ysibn9nq0k8de4po3vx532 FOREIGN KEY (PARENT_CHART_OF_ACCOUNT_ID) REFERENCES CHART_OF_ACCOUNT (CHART_OF_ACCOUNT_ID);

ALTER TABLE CHART_OF_ACCOUNT_CATEGORY
  ADD CONSTRAINT FKbxq8eqi3d1bqur3qgjrw9c8dd FOREIGN KEY (PARENT_CHART_OF_ACCOUNT_CATEGORY_ID) REFERENCES CHART_OF_ACCOUNT_CATEGORY (CHART_OF_ACCOUNT_CATEGORY_ID);

ALTER TABLE COAC_TRANSACTION_CATEGORY
  ADD CONSTRAINT FKfjw8t7ic9303jechkbhfb4r3o FOREIGN KEY (CHART_OF_ACCOUNT_CATEGORY_ID) REFERENCES CHART_OF_ACCOUNT_CATEGORY (CHART_OF_ACCOUNT_CATEGORY_ID);

ALTER TABLE COA_COA_CATEGORY
  ADD CONSTRAINT FK5nruai6t6flgrjfjv9dfnaru5 FOREIGN KEY (CHART_OF_ACCOUNT_CATEGORY_ID) REFERENCES CHART_OF_ACCOUNT_CATEGORY (CHART_OF_ACCOUNT_CATEGORY_ID),
  ADD CONSTRAINT FK7fj2lusnqcaj66ax8gjfcxf59 FOREIGN KEY (CHART_OF_ACCOUNT_ID) REFERENCES CHART_OF_ACCOUNT (CHART_OF_ACCOUNT_ID);

ALTER TABLE COMPANY
  ADD CONSTRAINT FK5v56uyx5n3yqgp1oihb0yhj3n FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE),
  ADD CONSTRAINT FKbg6xkc6pgeldfwhk39xm3fwvm FOREIGN KEY (INVOICING_COUNTRY_CODE) REFERENCES COUNTRY (COUNTRY_CODE),
  ADD CONSTRAINT FKfg5i2mio7279ck8xsmo6q52qg FOREIGN KEY (COMPANY_COUNTRY_CODE) REFERENCES COUNTRY (COUNTRY_CODE),
  ADD CONSTRAINT FKnqq74rxx13yescw08lxq7qely FOREIGN KEY (COMPANY_TYPE_CODE) REFERENCES COMPANY_TYPE (COMPANY_TYPE_CODE),
  ADD CONSTRAINT FKp8uoqhxahoirfycrtlkx3jbek FOREIGN KEY (INDUSTRY_TYPE_CODE) REFERENCES INDUSTRY_TYPE (INDUSTRY_TYPE_CODE);

ALTER TABLE CONTACT
  ADD CONSTRAINT FK36l0okantgoy213p9k62m4gxd FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY (COUNTRY_CODE),
  ADD CONSTRAINT FK9leffbmaeuqf01qi4k9tli7t1 FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE),
  ADD CONSTRAINT FKrvoavc583kticwfy5xoioytqf FOREIGN KEY (STATE_ID) REFERENCES STATE (STATE_ID);

ALTER TABLE COUNTRY
  ADD CONSTRAINT FK3y7owjhdlh9raaerjolmremxq FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE);

ALTER TABLE CUSTOMER_INVOICE_RECEIPT
  ADD CONSTRAINT FK1t89wcd8sy641i8a53b2bcrf1 FOREIGN KEY (RECEIPT_ID) REFERENCES RECEIPT (ID),
  ADD CONSTRAINT FK1w519064bksnojirx1fddlups FOREIGN KEY (CUSTOMER_INVOICE_ID) REFERENCES INVOICE (ID);

ALTER TABLE EMPLOYEE
  ADD CONSTRAINT FK10udip6rb915p044ax50gtemn FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE);

ALTER TABLE EXPENSE
  ADD CONSTRAINT FK1h4m0sxriyj8h9y9mv5wqgsah FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
  ADD CONSTRAINT FK6ape53fdcjqaoh9mgkm5tjeow FOREIGN KEY (TRANSACTION_CATEGORY_CODE) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID),
  ADD CONSTRAINT FK833rj6bfe5fs104novi50dj08 FOREIGN KEY (VAT_ID) REFERENCES VAT_CATEGORY (ID),
  ADD CONSTRAINT FK8o9jahxc8ff8whom01rns88w8 FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE),
  ADD CONSTRAINT FK8oasudvy4e86biit7kxxitdfd FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT (BANK_ACCOUNT_ID),
  ADD CONSTRAINT FKem8s6ne2t5amugd8vwyru9a10 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID);

ALTER TABLE EXPLANATION_STATUS
  ADD CONSTRAINT FK6akb0jbeki4mw33b2x6b0xh47 FOREIGN KEY (RECONSILE_JOURNAL_ID) REFERENCES JOURNAL (ID),
  ADD CONSTRAINT FKkj46hmgdeim6nqbsk4uujt0ql FOREIGN KEY (RECONSILE_JOURNAL_ID) REFERENCES JOURNAL (ID),
  ADD CONSTRAINT FKqieicwxm9x7q9vs1mcqve5tgu FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTON (TRANSACTION_ID),
  ADD CONSTRAINT FKsbltb842k4hgrmpcg6a66oywp FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (ID);

ALTER TABLE IMPORTED_DRAFT_TRANSACTON
  ADD CONSTRAINT FKhlqsar5v2ll8dilawrltf5k8d FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT (BANK_ACCOUNT_ID);

ALTER TABLE INVOICE
  ADD CONSTRAINT FKaclrvrkqd1ijj7hoyswu47ltk FOREIGN KEY (DOCUMENT_TEMPLATE_ID) REFERENCES DOCUMENT_TEMPLATE (ID),
  ADD CONSTRAINT FKi0v8e8yn1e6u81x56egmsns5h FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID),
  ADD CONSTRAINT FKjdl5oc2mqtx4wux9blw0beyst FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
  ADD CONSTRAINT FKlxgj2wewrvmp53hp4s25khm7y FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE);

ALTER TABLE INVOICE_LINE_ITEM
  ADD CONSTRAINT FK1vtja97apxmby178xm9a7p5ot FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
  ADD CONSTRAINT FK3us8ikqirbfv33g8stdxpkufi FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (ID),
  ADD CONSTRAINT FKoo2qdo7l6ijg1r06ph5u4g29w FOREIGN KEY (TRANSACTION_CATEGORY_ID) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID),
  ADD CONSTRAINT FKpwx0oqq7k62wy90jsoae397si FOREIGN KEY (VAT_ID) REFERENCES VAT_CATEGORY (ID);

ALTER TABLE JOURNAL
  ADD CONSTRAINT FK8fofiubaq7ywt9mhhuhirnaut FOREIGN KEY (RECONSILE_JOURNAL_ID) REFERENCES TRANSACTON (TRANSACTION_ID),
  ADD CONSTRAINT FKntbalkvf4pf72ok9scg0wybqu FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_CODE);

ALTER TABLE JOURNAL_LINE_ITEM
  ADD CONSTRAINT FK3nvxtauc7k1f22r909vwvit0j FOREIGN KEY (VAT_CATEGORY) REFERENCES VAT_CATEGORY (ID),
  ADD CONSTRAINT FK897i7s6k2ftgwr3y0tbleqmsw FOREIGN KEY (JOURNAL_ID) REFERENCES JOURNAL (ID),
  ADD CONSTRAINT FKl512nlsls7necq7n9lw8ly6wb FOREIGN KEY (CONTACT) REFERENCES CONTACT (CONTACT_ID),
  ADD CONSTRAINT FKm7q0sr3jlg0nn62ty2n6d1sd FOREIGN KEY (TRANSACTION_CATEGORY) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID);

ALTER TABLE LEADGER_ENTRY
  ADD CONSTRAINT FKot3b2pdxulwdl86x0d8t46olv FOREIGN KEY (TRANSACTION_CATEGORY) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID);

ALTER TABLE PAYMENT
  ADD CONSTRAINT FK1xc4pqahlfvai3uqnjdxro2cg FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (ID),
  ADD CONSTRAINT FK477s0wc9n8l6oupyoqk4v2g3c FOREIGN KEY (DEPOSITE_TO_TRANSACTION_CATEGORY_ID) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID),
  ADD CONSTRAINT FKde11t0tvotbsq3fyvyqoeakem FOREIGN KEY (BANK_ID) REFERENCES BANK_ACCOUNT (BANK_ACCOUNT_ID),
  ADD CONSTRAINT FKej5ukmej5ganhkov18p08dbv0 FOREIGN KEY (SUPPLIER_ID) REFERENCES CONTACT (CONTACT_ID),
  ADD CONSTRAINT FKhfkwm4145f62l0p7hevx9pkfh FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
  ADD CONSTRAINT FKmyfaof47mpq1xt4oka050ia1v FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE);

ALTER TABLE PRODUCT
  ADD CONSTRAINT FKb1fvg8k36s1hkw7bph4xdicwb FOREIGN KEY (PRODUCT_CATEGORY) REFERENCES PRODUCT_CATEGORY (ID),
  ADD CONSTRAINT FKdtukqv2nkx3ql9dn175w3m5vi FOREIGN KEY (PRODUCT_VAT) REFERENCES VAT_CATEGORY (ID),
  ADD CONSTRAINT FKgke93hg6nxjv8sphh2cgay1l7 FOREIGN KEY (PRODUCT_WAREHOUSE) REFERENCES PRODUCT_WAREHOUSE (WAREHOUSE_ID);

ALTER TABLE PRODUCT_LINE_ITEM
  ADD CONSTRAINT FK49pfehurx3mnt3ut4gygv57pp FOREIGN KEY (TRANSACTION_CATEGORY_ID) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID),
  ADD CONSTRAINT FKax4sf8pl7n9tgbl8dbonlyq9s FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);

ALTER TABLE PROJECT
  ADD CONSTRAINT FKonsoyqqfrc36bnhs9v2jrn2m6 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID),
  ADD CONSTRAINT FKsl1b7xwfoip3qaaxqxou4k59m FOREIGN KEY (LANGUAGE_CODE) REFERENCES LANGUAGE (LANGUAGE_CODE),
  ADD CONSTRAINT FKsystjmngpibcub97hnelxglb5 FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE);

ALTER TABLE PURCHASE
  ADD CONSTRAINT FK688w41idqte3v1x4xxd7cuh7o FOREIGN KEY (TRANSACTION_CATEGORY_CODE) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID),
  ADD CONSTRAINT FK8xoirx9xofqpeg9d0ym4l3wfc FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID),
  ADD CONSTRAINT FKero9wumttdv7rigt7b3otunr6 FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
  ADD CONSTRAINT FKmfhdq6vbfarljm2qvd0tc18r7 FOREIGN KEY (TRANSACTION_TYPE_CODE) REFERENCES CHART_OF_ACCOUNT (CHART_OF_ACCOUNT_ID),
  ADD CONSTRAINT FKquuc99nspry8dd9sqhrn9ck3w FOREIGN KEY (CLAIMANT_ID) REFERENCES USER (USER_ID),
  ADD CONSTRAINT FKsaceh3lwoomi56ieeqncrl42d FOREIGN KEY (TRANSACTION_TYPE_CODE) REFERENCES CHART_OF_ACCOUNT (CHART_OF_ACCOUNT_ID),
  ADD CONSTRAINT FKsykk14n7iv1sspx7k3736e8w2 FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE);

ALTER TABLE PURCHASE_LINE_ITEM
  ADD CONSTRAINT FK7kan4atehkdj1avwma5n4jsgj FOREIGN KEY (PURCHASE_LINE_ITEM_VAT_ID) REFERENCES VAT_CATEGORY (ID),
  ADD CONSTRAINT FK8g781cnubw1y3yey7l765dd9y FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE (PURCHASE_ID),
  ADD CONSTRAINT FKfqsooxudbgeyxrkm0d0sieeqf FOREIGN KEY (PURCHASE_LINE_ITEM_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);

ALTER TABLE RECEIPT
  ADD CONSTRAINT FK51n4ndnvkek113y3eo85rlvxh FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (ID),
  ADD CONSTRAINT FKkhhdki7s8y02tu4ufdutgr60u FOREIGN KEY (DEPOSITE_TO_TRANSACTION_CATEGORY_ID) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID),
  ADD CONSTRAINT FKr1fvo9bhp9dxux6dc27bgjr9k FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);

ALTER TABLE RECONCILE_CATEGORY
  ADD CONSTRAINT FKkvyqtaicn740d1w4caco178vm FOREIGN KEY (PARENT_RECONCILE_CATEGORY_ID) REFERENCES RECONCILE_CATEGORY (ID);

ALTER TABLE STATE
  ADD CONSTRAINT FKi312viy9ek534eyiruaad6ixf FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (COUNTRY_CODE);

ALTER TABLE SUPPLIER_INVOICE_PAYMENT
  ADD CONSTRAINT FK4ph4idew15w6smdgom59kbhxg FOREIGN KEY (SUPPLIER_INVOICE_ID) REFERENCES INVOICE (ID),
  ADD CONSTRAINT FKfex7pckbnnbh9bruwgjcy2spr FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (ID);

ALTER TABLE TRANSACTION_CATEGORY
  ADD CONSTRAINT FK26p0l1ohbho2jsyb8kay3oogy FOREIGN KEY (CHART_OF_ACCOUNT_ID) REFERENCES CHART_OF_ACCOUNT (CHART_OF_ACCOUNT_ID),
  ADD CONSTRAINT FKlbbqyxeqlk21vxhiic461yy26 FOREIGN KEY (CHART_OF_ACCOUNT_ID) REFERENCES CHART_OF_ACCOUNT (CHART_OF_ACCOUNT_ID),
  ADD CONSTRAINT FKlxx3gnpeg77g538j5gom3fubu FOREIGN KEY (VAT_CATEGORY_CODE) REFERENCES VAT_CATEGORY (ID),
  ADD CONSTRAINT FKqp7r3h1eoj9jl1n5rmt1pwnmj FOREIGN KEY (PARENT_TRANSACTION_CATEGORY_CODE) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID);

ALTER TABLE TRANSACTION_CATEGORY_BALANCE
  ADD CONSTRAINT FK79g3xavym27ekuyw995yqlvrd FOREIGN KEY (TRANSACTION_CATEGORY_ID) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID);

ALTER TABLE TRANSACTION_CATEGORY_CLOSING_BALANCE
  ADD CONSTRAINT FK79g3xavym27ekuyw995yqldrv FOREIGN KEY (TRANSACTION_CATEGORY_ID) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID);

ALTER TABLE TRANSACTION_DATA_COL_MAPPING
  ADD CONSTRAINT FK31oyusni6lge51kccyw03g660 FOREIGN KEY (DATE_FORMAT_ID) REFERENCES DATE_FORMAT (ID),
  ADD CONSTRAINT FKsg4bm2mrbu8m4vrf75392ussh FOREIGN KEY (TRANSACTION_DATA_COL_MAPPING_ID) REFERENCES TRANSACTION_PARSING_SETTING (ID);

ALTER TABLE TRANSACTION_PARSING_SETTING
  ADD CONSTRAINT FKo8c5ktmgxtuh0pr167p4gm50n FOREIGN KEY (DATE_FORMAT_ID) REFERENCES DATE_FORMAT (ID);

ALTER TABLE TRANSACTON
  ADD CONSTRAINT FK1o99egk2prramm7j3qh4r52qx FOREIGN KEY (VAT_ID) REFERENCES VAT_CATEGORY (ID),
  ADD CONSTRAINT FK34ln1pxogaxkhp2ws2e8dq9my FOREIGN KEY (EXPLINTION_EMPLOYEE_ID) REFERENCES EMPLOYEE (ID),
  ADD CONSTRAINT FK56rhnp6nd3nru4845o863vt6o FOREIGN KEY (PARENT_TRANSACTION) REFERENCES TRANSACTON (TRANSACTION_ID),
  ADD CONSTRAINT FK9bxc5njntwhpd9vdjb02pdc24 FOREIGN KEY (EXPLINTION_VENDOR_CONTACT_ID) REFERENCES CONTACT (CONTACT_ID),
  ADD CONSTRAINT FK9kk6m5arfjny7gk7wraj0vkeo FOREIGN KEY (COA_CATEGORY_ID) REFERENCES CHART_OF_ACCOUNT_CATEGORY (CHART_OF_ACCOUNT_CATEGORY_ID),
  ADD CONSTRAINT FK9xky8eec7uwwi1o0gf2r1cn1e FOREIGN KEY (TRANSACTION_TYPE_CODE) REFERENCES CHART_OF_ACCOUNT (CHART_OF_ACCOUNT_ID),
  ADD CONSTRAINT FKf22amenxf45h7oldv5w8avvl2 FOREIGN KEY (EXPLANATION_STATUS_CODE) REFERENCES EXPLANATION_STATUS (EXPLANATION_STATUS_CODE),
  ADD CONSTRAINT FKf82fpo3aojpcvofvstb1f4i3e FOREIGN KEY (EXPLAINED_PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
  ADD CONSTRAINT FKinfcruhes0vn2l7aan90fw2xu FOREIGN KEY (EXPLINTION_BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT (BANK_ACCOUNT_ID),
  ADD CONSTRAINT FKkmrn5djmwm30equrdipotnqmg FOREIGN KEY (TRANSACTION_TYPE_CODE) REFERENCES CHART_OF_ACCOUNT (CHART_OF_ACCOUNT_ID),
  ADD CONSTRAINT FKn0ptk14chjd7sig1hce277m9a FOREIGN KEY (EXPLINTION_CUSTOMER_CONTACT_ID) REFERENCES CONTACT (CONTACT_ID),
  ADD CONSTRAINT FKnhy5qd2lutaoaq9858ss7odf4 FOREIGN KEY (EXPLAINED_TRANSACTION_CATEGORY_CODE) REFERENCES TRANSACTION_CATEGORY (TRANSACTION_CATEGORY_ID),
  ADD CONSTRAINT FKs61ftx9ipvaoy4ya5fc55se90 FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT (BANK_ACCOUNT_ID);

ALTER TABLE USER
  ADD CONSTRAINT FKdup5w9kutiunoewb3bf9w1u0w FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (COMPANY_ID),
  ADD CONSTRAINT FKe4ndlf6wkwgphdwe7tbrift9u FOREIGN KEY (EMPLOYEE_ID) REFERENCES CONTACT (CONTACT_ID),
  ADD CONSTRAINT FKkaa9gg6h8pjd26u4ejhxg2lp6 FOREIGN KEY (ROLE_CODE) REFERENCES ROLE (ROLE_CODE);
COMMIT;

--changeset 24/10/2020 zain:ddl-2
create table SIMPLEVAT_MODULES (SIMPLEVAT_MODULE_ID integer not null, SIMPLEVAT_MODULE_NAME varchar(255) not null, DEFAULT_FLAG char(1) default 'N' not null, DELETE_FLAG bit default 0 not null, ORDER_SEQUENCE integer, PARENT_SIMPLEVAT_MODULE_ID integer, EDITABLE_FLAG bit default 0 not null, SELECTABLE_FLAG bit default 0 not null,MODULE_TYPE varchar(255) not null, primary key (SIMPLEVAT_MODULE_ID)) engine=InnoDB DEFAULT CHARSET=utf8;

create table ROLE_MODULE_RELATION (ID integer not null auto_increment, SIMPLEVAT_MODULE_ID integer, ROLE_CODE integer, primary key (ID)) engine=InnoDB DEFAULT CHARSET=utf8;

--changeset 05/11/2020 zain:ddl-3
ALTER TABLE CONFIGURATION CHANGE VALUE VALUE TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

--changeset 14/11/2020 zain:ddl-4
ALTER TABLE CONVERTED_CURRENCY CHANGE CURRENCY_CONVERSION_ID CURRENCY_CONVERSION_ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE CONVERTED_CURRENCY ADD DELETE_FLAG bit(1) DEFAULT b'0';

--changeset 15/11/2020 zain:ddl-5
ALTER TABLE INVOICE ADD EXCHANGE_RATE decimal(19,9) DEFAULT NULL;

ALTER TABLE EXPENSE ADD EXCHANGE_RATE decimal(19,9) DEFAULT NULL;

--changeset 17/11/2020 zain:ddl-6
ALTER TABLE CONVERTED_CURRENCY
ADD CONSTRAINT FK1 FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE),
ADD CONSTRAINT FK2 FOREIGN KEY (CURRENCY_CODE_CONVERTED_TO) REFERENCES CURRENCY (CURRENCY_CODE);

--changeset 19/11/2020 zain:ddl-7
CREATE TABLE CUSTOMIZE_INVOICE_TEMPLATE (ID int(11) NOT NULL, CREATED_BY int(11) NOT NULL, DELETE_FLAG bit(1) NOT NULL DEFAULT b'0', TYPE int(11) NOT NULL, PREFIX varchar(255) NOT NULL, SUFFIX int(11) NOT NULL, PRIMARY KEY (ID)) engine=InnoDB DEFAULT CHARSET=utf8;
