apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "helm-frontend.fullname" . }}-certificate
  namespace: default
spec:
  secretName: {{ .secretName }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    # The issuer created previously
    name: {{ .Values.clusterIssuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.maindomain }}
  dnsNames:
	{{- range .hosts }}
	- {{ . | quote }}
  	{{- end }}
