apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "helm-frontend.fullname" . }}-certificate

spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
  # The issuer created previously
    name: {{ .Values.clusterIssuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.maindomain }}
  {{- range .Values.ingress.tls }}
  secretName: {{ .secretName }}
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}




