apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "helm-frontend.fullname" . }}-certificate
  namespace: default
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
	# The issuer created previously
	name: simbiz-app-letsencrypt-staging
	kind: ClusterIssuer
  commonName: simbiz.app
  {{- range .Values.ingress.tls }}
  secretName: {{ .secretName }}
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}




