apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: simplevat
  name: simplevat-dev-rep
  namespace: simplevat-dev
spec:
  replicas: 3
  selector:
    app: simplevat
    deployment: v-1
  template:
    metadata:
      labels:
        app: simplevat
        deployment: v-1
    spec:
      containers:
        - name: simplevat
          image: gcr.io/gtt-k8s/simplevat:0-0-1-rc-36
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          env:
            - name: SIMPLEVAT_SMTP_USER
              value: support@simplevat.com
            - name: SIMPLEVAT_SMTP_PASS
              value: $impleVat@123
            - name: SIMPLEVAT_SMTP_HOST
              value: smtp.gmail.com
            - name: SIMPLEVAT_SMTP_PORT
              value: "587"
            - name: SIMPLEVAT_SMTP_AUTH
              value: "true"
            - name: SIMPLEVAT_SMTP_STARTTLS_ENABLE
              value: "true"
            - name: SIMPLEVAT_ENVIRONMENT
              value: dev
            - name: SIMPLEVAT_SUBDOMAIN
              value: dev
            - name: SIMPLEVAT_TOKEN
              value: XXXX
            - name: SIMPLEVAT_RELEASE
              value: 0-0-1-rc-05
            - name: SIMPLEVAT_HOST
              value: http://k8s.dev.simplevat.com
            - name: SIMPLEVAT_DB_HOST
              value: gtt-prod-cloudsql-proxy-service.cloudsql-proxy
            - name: SIMPLEVAT_DB
              value: simplevat_db
            - name: SIMPLEVAT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: SIMPLEVAT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
