apiVersion: v1
kind: Service
metadata:
  name: simplevat-service-dev
  namespace: simplevat-dev
  labels:
    app: simplevat-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: simplevat-rc-dev
