apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simplevat-ingress-dev
  namespace: simplevat-dev
  annotations:
    kubernetes.io/ingress.global-static-ip-name: simplevat-dev-ip
spec:
  backend:
    serviceName: simplevat-service-dev
    servicePort: 80
  rules:
    - host: k8s.dev.simplevat.com
      http:
        paths:
          - backend:
              serviceName: simplevat-service-dev
              servicePort: 80
            path: /*
